#+SETUPFILE: ./export_template.org
#+TITLE: Conversation
* Why study conversation?
- Tt seems that everyone can conduct conversation
- There are basic patterns and techniques
  - People do not adopt a totally new or different system for
    communicating in any given situation
  - Conversational skill is adopted to other forms of interactive talk
** Sociology
#+BEGIN_QUOTE
"What I call social facts are the ways of acting, thinking, and
feeling external to the individual, and endowed with a power of
coercion, by reason of which they control him"

- Emile Durkheim
#+END_QUOTE
*** Garfinkel's 'breaching' experiment
- Spend from 15 minutes to an hour in their homes imagining that you
  are boarders and act out this assumption. You should conduct
  yourself in circumspect and polite fashion. Avoid getting personal,
  to use formal address, to speak only when spoken to.
- Clarify everything which may not be immediately understandable for
  the non-family members

We obey certain social rules, and make underlying social assumptions
in all our interactions. This brings about social order.
*** What is a social situation?
#+BEGIN_QUOTE
I would define a social situation as an environment of mutual
monitoring possibilities... wherein an individual will find themselves
accessible to the naked senses of all others who present -- and
similarly, find those others accessible to him.

- Erving Goffman
#+END_QUOTE
** Linguistics
- Traditional linguistics see the language as an internal cognitive
  representation of individuals.
- Grammatical categories reflect cultural patterns of thinking and
  acting -- Boas, Sapir
- Encourage inquiry to speech event, speech situation, speech
  community -- Gumperz, Hymes
* Conversation Analysis
Talk is highly organized; conversation analysis involves understanding
how conversational practices fit together in highly intricate ways.
** Basic assumptions
1. Order is produced orderliness
2. Order is produced, situated, and occasioned
3. Order is repeatable and recurrent
** Characteristics of Conversation
- Interactive
  - Take turns -- sequential activity
  - Talk is tied to prior and future turns
  - Each turn makes contributions to the conversation
- Locally managed
  - The organization and content of a conversation are not
    predetermined or planned
- Mundane
  - Commonplace and practical
  - Use language
** What we ask in CA
- What is the speaker doing in saying this and in saying it in this
  way?
- We do not ask what it means. We ask what it does.
* Turn taking
We are very attuned to grammatical intonation, so we know when to
start speaking.
