* Introduction                                                     :noexport:
** Definitions
Cyberethics - study of moral, legal and social issues involving cybertechnology.
Cybertechnology - wide range of computing and communication devices.
** 4 phases
*** 1950s and 1960s
1. Building of ENIAC, huge mainframe computers, unconnected
2. Can machines think? Should these be invented?
3. What does it mean to be human?
4. Privacy threats, govt surveillance
*** 1970s and 1980s
1. networked computers, facilitate communication of information
2. Intellectual property, personal privacy, computer crime
*** 1990-present
1. World Wide Web
2. Free speech, anonymity
3. Geographical boundaries, legal jurisdiction
*** present-near future
1. Biotech, RFID
2. increased use of autonomous systems
** Cyberethics as different kinds of ethics
| Type          | Disciplines                        | Issues                                                                                     |
|---------------+------------------------------------+--------------------------------------------------------------------------------------------|
| Professional  | CS/Engineering/Information Science | Prof. Responsibility                                                                       |
|               |                                    | System Reliability                                                                         |
|               |                                    | Codes of Conduct                                                                           |
| Philosophical | Philosophy/Law                     | Privacy and Anonymity                                                                      |
|               |                                    | Intellectual Property                                                                      |
|               |                                    | Free Speech                                                                                |
| Sociological  | Sociology/Behavioural Sciences     | Impact of cybertech on govt/financial/educational institutions and sociodemographic groups |
** Methodology
1. Identify a practice involving cybertech, or a controversial feature
   - Disclose hidden/opaque features
   - Assess descriptive components of ethical issues via sociological implications
   - Analyze normative elements, determine if guidelines/policies can resolve the issue
2. Analyze ethical issue by clarifying concepts and situating it in context
   - If a policy vacuum exists, go next substep, if not go to step 3
   - Clear up any conceptual muddles involving policy vacuum
3. Deliberate on ethical issue
   - Apply one or more ethical theories to the analysis
   - Justify the position you reach via sound logical analysis
* Morality
1. Directives that guide our conduct as individuals
2. Social policies framed at the macrolevel

Moral systems are evaluated against standards called /principles/.

Morality is:
1. Public
   - Rules are public
   - Everyone is obligated to partake in a moral system
2. Informal
   - Has no formal authoritative judges presiding over it
3. Impartial
   - Moral rules are ideally designed to apply equitably to all participants
4. Rational
   - The system is based on principles of logical reason
* Values
1. Instrumental
   - Provide external benefit (eg. computers etc)
2. Intrinsic
   - Valued for their own sake (eg. life, happiness)
* Ethical Theories
** Consequence-based (Utilitarianism) 
Some have argued that the primary goal of a moral system is to produce
desirable consequences or outcomes for its members. For these
ethicists, the consequences (i.e., the ends achieved) of actions and
policies provide the ultimate standard against which moral decisions
must be evaluated

*** Utilitarianism
#+BEGIN_QUOTE
An individual act (X) or a social policy (Y) is morally permissible if
the consequences that result from (X) or (Y) produce the greatest
amount of good for the greatest number of persons affected by the act
or policy.
#+END_QUOTE

 1. Social utility is superior to alternative criteria for evaluating
    moral systems.
 2. Social utility can be measured by the amount of happiness
    produced.

Assumes:
1. All people desire happiness.
2. Happiness is an intrinsic good that is desired for its own sake.

*Act Utilitarianism:*

#+BEGIN_QUOTE
An act, X, is morally permissible if the consequences produced by
doing X result in the greatest good for the greatest number of persons
affected by Act X.
#+END_QUOTE

*Rule Utilitarianism:*

#+BEGIN_QUOTE
An act, X, is morally permissible if the consequences of following the
general rule, Y, of which act X is an instance, would bring about the
greatest good for the greatest number.
#+END_QUOTE

*Critic against Utilitarianism:*

1. Morality is basically tied to the production of happiness or pleasure.
2. Morality can ultimately be decided by consequences (of either acts
   or policies).

Critics of utilitarianism argue that morality can be grounded neither
in consequences

** Duty-based (Deontology)
Kant points out that, in some instances, performing our duties may
result in our being unhappy and may not necessarily lead to
consequences that are considered desirable.

Kant bases deontology on two premises:
1. Our nature as rational creatures
   - Rationality is what separates us from other kinds of creatures. If
     our primary nature were to merely seek happiness or pleasure, we
     would be indistinguishable from other creatures.
   - Rational nature reveals certain duties or obligations to each
     other as "rational beings"
2. Human beings are ends-in-themselves
   - A genuinely moral system would never permit some humans to be
     treated as means to the ends of others
   - We have a duty to treat fellow humans as ends; each individual
     has the same moral worth

*Categorical Imperative*:

#+BEGIN_QUOTE
Act always on that maxim or principle (or rule) that can be
universally binding, without exception, for all human beings.
#+END_QUOTE

This forms a system of universality and impartiality. The objective
rule to be followed—that is, the litmus test for determining when an
action will have moral worth—is whether the act complies with the
categorical imperative, and whether it is universal and impartial.

*Act Deontology*:

Ross argues that when two or more moral duties
clash, we have to look at individual situations in order to determine
which duty will override another.

Ross believes that we have certain prima facie (or self-evident)
duties, which, all things being equal, we must follow. He provides a
list of prima facie duties such as honesty, benevolence, justice, and
so forth.

1. Reflect on the competing prima facie duties. 
2. Weigh the evidence at hand to determine which course of action
   would be required in a particular circumstance.

** Contract-based
In his classic work /Leviathan/, Hobbes describes an original
“premoral” state that he calls the “state of nature.” It is premoral
because there are no moral (or legal) rules yet in existence. In this
state, each individual is free to act in ways that satisfy his or her
own natural desires. According to Hobbes, our natural (or physical)
constitution is such that in the state of nature we act in ways that
will enable us to satisfy our desires (or appetites) and to avoid what
Hobbes calls our "aversions."

Hobbes believes that we are willing to surrender some of our
“absolute” freedoms to a sovereign. In return, we receive many
benefits, including a system of rules and laws that are designed and
enforced to protect individuals from being harmed by other members of
the system.

We see that it is in our individual self-interest to develop a moral
system with rules.

*** Criticisms
Some critics, such as Pojman (2006), point out that contract-based
theories provide the foundation for only a minimalist morality. They
are minimalist in the sense that we are obligated to behave morally
only where an explicit or formal contract exists. So if I have no
express contract with you, or if a country such as the United States
has no explicit contract with a developing nation, there is no moral
obligation for me to help you or for the United States to come to the
aid of that developing nation.

** Rights-Based
- humans possess some natural rights
- Two kinds of legal rights: positive rights and negative rights.
  Having a negative right to something simply means that one has the
  right not to be interfered with in carrying out the privileges
  associated with that right.
- Positive rights more rare and harder to justify.

** Character-based
Because virtue ethics focuses primarily on character development and
moral educa- tion, it does not need to rely on a system of formal
rules.

Character-based ethical systems would most likely flourish in cultures
where the emphasis placed on community life is stronger than that
accorded to the role of individuals themselves.

 | Type of Theory                  | Advantages                                         | Disadvantages                                                 |
 |---------------------------------+----------------------------------------------------+---------------------------------------------------------------|
 | Consequence-based (Utilitarian) | Stresses promotion of happiness and utility        | Ignores concerns of justice for the minority population       |
 | Duty-based (deontology)         | Stresses the role of duty and respect for persons  | Underestimates the importance of happiness and social utility |
 | Contract-based (rights)         | Provides a motivation for morality                 | Ofers only a minimal morality                                 |
 | Character-based (virtue)        | Stresses character development and moral education | Depends on homogeneous standards for morality                 |

** Moor's Just Consequentialist Framework
1. Deliberate over various policies from an impartial point of view to
   determine whether they meet the criteria for being ethical
   policies. A policy is ethical, if it
   - does not cause any unnecessary harms to individuals and groups,
     and
   - supports individual rights, the fulfilling of duties, etc.
2. Select the best policy from the set of just policies arrived at in
   the deliberation stage by ranking ethical policies in terms of
   benefits and (justifiable) harms. In doing this, be sure to:
   - weigh carefully between the good consequences and bad
     consequences in the ethical policies, and
   - distinguish between disagreements about facts and disagreements
     about principles and values, when deciding which particular
     ethical policy should be adopted. (Knowledge about the facts
     surrounding a particular case should inform the decision-making
     process.)
