
1. LDA, DTM - don't work as well as deep learning model

LDA: list of important words for n topics
DTM: make LDA time variant

Problems: common wworks like "computer"... 

HITS algo, similar to PageRank

2 concepts, authors, keywords -> important authors say important
keywords

modified textrank

<NN>*<NN|NNS>

1. Author -> keyphrases
2. Keyphrase needs to be clustered LDA, Embedding
3. What is a trend? (coarser grain than keyphrase), hierachical
   agglomerate clustering

Couperin
* Connecting to SoC VPN
use openfortivpn.

#+BEGIN_SRC sh
  sudo openfortivpn webvpn.comp.nus.edu.sg:443 -u e0036913 -p pass --trusted-cert cert
#+END_SRC

* Setting up GPU cluster
1. Install Anaconda
2. Setup conda environment with required packages
3. conda env update
4. source activate fastai

* Current Methodology
1. Use TextRank algorithm
** TextRank
Prior to TextRank, use NLTK to extract noun phrases via Regex. Each
noun phrase is split further.
** RNN
Basic RNN is employed to use the first k sequential years to predict
the (k+1)th years score. The model takes the top 20 phrases for each
year, and the top 20 based on predictions from the RNN. It is expected
that the predicted phrases closely match the actual top 20 phrases of
the year.

A linear regression model is used as the baseline comparison.
** Definition of Trend
Considerations:

1. Research areas should have a strong foundation, but not be the
   most-discussed issue at the same time
2. Research areas should be gradually studied

\begin{equation*}
trend = a \times (x\textsubscript{k+1} - max(x\textsubscript{1}, ... , x\textsubscript{k})) + (1 - a) \times max(x\textsubscript{1}, ... , x\textsubscript{k})
\end{equation*}

* Keyphrase Extraction
Keyphrase extraction (KE) is the task of automatically extracting
descriptive phrases or concepts that represent the main topics of a
document.

In supervised approaches, a candidate phrase is encoded with a set of
features, such as /tf-idf/. One problem is that many of these manual
features are determined based on statistical information from
documents outside the target domain. Hence, it is essential to
automatically discover such features without relying on feature
engineering.
** SurfKE
*** Graph Construction
Build an undirected word graph, with words as vertices. There is an
edge between two words if the words co-occur within =w= contiguous
word tokens. The weight of the edge is computed based on the
co-occurence within a window of w successive tokens in the
document.
*** Learning Feature Representations
Learn a mapping function $f : V \rightarrow \mathbb{R}^{|V| \times d},
d \le |V|$ where d is a parameter specifying the number of dimensions
for the embeddings. The network feature learning model requires a
corpus and a vocabulary in order to learn a mapping of nodes to a
low-dimensional space of features. A biased sampled random walk
strategy is employed.
* Topical Hierarchy
[[file:~/Dropbox/NUS/UROP/CATHY_-_Construction_of_Topical_Hierarch.pdf][CATHY]]

CATHY - co-occurrence network clustering, recursively apply
CATHY to discover sub-topics

[[http://chbrown.github.io/kdd-2013-usb/kdd/p437.pdf][Phrase Mining Framework for Recursive Construction of a Topical Hierachy]]
* Topic Modeling
http://www.cs.columbia.edu/~blei/topicmodeling.html
** LDA
https://www.youtube.com/watch?v=FkckgwMHP2s
http://www.cs.columbia.edu/~blei/papers/Blei2012.pdf
*** Dirichlet Distribution
https://www2.ee.washington.edu/techsite/papers/documents/UWEETR-2010-0006.pdf

Dirichlet distribution is a family of continuous multivariate
probability distributions parameterized by a vector α of positive
reals.

\begin{equation}
  \theta \sim Dir(\alpha)
\end{equation}

\begin{equation}
  p(\theta) = \frac{1}{\beta(\alpha)} \prod_{i=1}^n \theta_i^{\alpha_i-1} I(\theta \in S)
\end{equation}

Where $\theta = (\theta_1, \theta_2, \hdots, \theta_n), \alpha = (\alpha_1, \alpha_2, \hdots, \alpha_n), \alpha_i > 0$ and

\begin{equation}
  S = \left\{x \in \mathbb{R}^n : x_i \ge 0, \sum_{i=1}^{n} x_i = 1 \right\}
\end{equation}

and 
$\frac{1}{\beta(\alpha)} =
\frac{\Gamma(\alpha_0)}{\Gamma(\alpha_1)\Gamma(\alpha_2)\hdots\Gamma(\alpha_n)}$

The infinite-dimensional generalization of the Dirichlet distribution
is the Dirichlet process.

The Dirichlet distribution is the conjugate prior distribution of the
categorical distribution (a generic discrete probability distribution
with a given number of possible outcomes) and multinomial distribution
(the distribution over observed counts of each possible category in a
set of categorically distributed observations). This means that if a
data point has either a categorical or multinomial distribution, and
the prior distribution of the distribution's parameter (the vector of
probabilities that generates the data point) is distributed as a
Dirichlet, then the posterior distribution of the parameter is also a
Dirichlet.
*** Exploring a Corpus with the posterior distribution
Quantities needed for exploring a corpus are the posterior
expectations of hidden variables. Each of these quantities are
conditioned on the observed corpus.

Visualizing a topic is done by visualizing the posterior topics
through their per-topic probabilities $\hat{\beta}$.

Visualizing a document uses the posterior topic proportions
$\hat{\theta}_{d,k}$ and the posterior topic assignments
$\hat{z}_{d,k}$.

Finding similar documents can be done through the /Hellinger
distance/:

\begin{align*}
  D_{d,k} = \sum_{k=1}^K \left( \sqrt{\hat{\theta}_{d,k}} - \sqrt{\hat{\theta}_{f,k}}\right)^2
\end{align*}
*** Posterior Inference
**** Mean Field Variational Inference
Approximate intractable posterior distribution with a simpler
distribution containing free variational parameters. These parameters
are fit to approximate the true posterior.

In contrast to the true posterior, the mean field variational
distribution for LDA is one where the variables are independent of
each other, with and each governed by a different variational
parameter.

We fit the variational parameters to minimise the KL-divergence to the
true posterior.

The general approach to mean-field variational methods - update each
variational parameter with the parameter given by the expectation of
the true posterior under the variational distribution - is applicable
when the conditional distribution of each variable is the exponential
family.
*** Shortcomings
- strong, potentially invalid statistical assumptions:
  - topics have no correlation to one another (dirichlet assumes
    nearly independent)
    - solution: CTM: use a logistic normal distribution
  - assumes order of documents don't matter
    - solution: DTM: use logistic normal distribution to model topics
      evolving over time
** TopicRNN
http://www.columbia.edu/~jwp2128/Papers/DiengWangetal2017.pdf 

In TopicRNN, latent topic models are used to capture global semantic
dependencies so that the RNN can focus its modeling capacity on the
local dynamics of the sequences

** TODO Visualization of Perplexity for topic models as a potential topic?
