#+setupfile:./hugo_setup.org
#+roam_key: https://www.youtube.com/watch?v=btmJtThWmhA
#+hugo_slug: causality_part_1_bernhard_scholkopf_mlss_2020_tubingen_youtube
#+roam_tags: website
#+title: Causality, part 1 - Bernhard Schölkopf - MLSS 2020, Tübingen - YouTube

- source :: https://www.youtube.com/watch?v=btmJtThWmhA&feature=youtu.be

* Background and Motivation

Consider a dataset of temperature $t$ vs altitude $a$. We typically see that the
larger the altitude, the lower the temperature. How do we know if this is a
causal effect?

1. Intervention: we can raise the city, and find that the temperature changes
2. Hypothetical intervention: expect that $t$ changes, since we can think of a
   physical mechanism $p(t|a)$ that is independent of $p(a)$. We expect that
   $p(t|a)$ is invariant across different countries in similar climate zone.

A "structural" relation not only explains the observed data; it captures a
structure connecting the variables.

An equation becomes structural by virtue of invariance to a domain of
modifications.

* [[file:structural_causal_model.org][Structural Causal Model]]
:PROPERTIES:
:ID:       7641ec39-6e89-4505-9363-d365b446a20a
:END:
