#+setupfile:./hugo_setup.org
#+hugo_slug: object_localization
#+title: Object Localization

Object localization is the task of determining the location of a target object
from input data. Broadly speaking, object localization can be classified into 3
different tasks:

- [[Localization without Classification]] :: the task is to produce potential regions for target objects, without knowing their categories
- [[Object Detection]] :: provide localization information of objects, along with their categories
- [[Object Instance Segmentation]] :: provide pixel-level segmentation of input data to different objects

* Localization without Classification
** 2D Methods

These methods consume 2D image inputs, usually RGB images. One simple 2D
localization without classification method is fitting 2D shape primitives, such
as rectangles or polygons. These are often used when the viewpoint of the camera
is fixed, resulting in constrained shapes for the target objects.

2D salient object detection locates and segments visually distinctive object
regions in a given image. Traditional methods rely on hand-crafted features and
low-level feature representations, but recent deep learning-based methods have
shown to outperform them.

*** TODO See Borji et al 2019 and Wang et al 2019 for surveys on 2D salient object detection

** 3D Methods
:PROPERTIES:
:ID:       da06dc73-2c5b-49a5-aee0-ebf9ec947e97
:END:

Similar to the 2D methods, 3D methods fit 3D shape primitives (such as with
[[file:ransac.org][RANSAC]]) or perform salient 3D object detection. However, 3D methods deal instead
with point-cloud inputs.

* Object Detection
:PROPERTIES:
:ID:       33219862-d5f0-43e2-bddb-84a1a8a118c1
:END:

The popular way of performing object detection is a two-staged process. Object
proposals are generated, and the proposals are ranked and classified.
Deep-learning methods such as R-CNN and their variants can be trained end-to-end
to generate detection proposals.

One-stage methods such as YOLO are able to predict bounding boxes and class
scores in one evaluation.

3D object detection methods often deal with objects on known shapes. The problem
is transformed into a detection and 6D object pose estimation problem. The 6D
pose of the object can be achieved through [[file:local_registration.org][local registration]].

** Generating 3D Object Proposals

Frustum-based methods generates object proposals using 2D object detectors.
Global regression-based methods use feature representations extracted from a
single, or multiple inputs.

*** TODO See Guo et al 2020 for a survey on 3D object detection

* Object Instance Segmentation

Instance segmentation methods can also be classified into one-stage methods and
two-stage methods. Two-stage methods first generate region proposals.
