:PROPERTIES:
:ID:       61723832-db9f-4ae1-857b-45c83e942c8a
:END:
#+setupfile:./hugo_setup.org
#+hugo_slug: object_pose_estimation
#+title: Object Pose Estimation

Object pose estimation is the task of obtaining the 6D pose of target objects.
For 2D planar grasps, target objects are constrained in a 2D workspace, so the
6D object pose is reduced to a 2D position and the in-plane rotation angle.

* Correspondence-based methods
:PROPERTIES:
:ID:       59069a0a-e82b-4226-a36a-d6b0d2820311
:END:

Correspondence-based methods find correspondences between the observed input
data, and some existing 3D object model. The 6D object pose can then be
recovered through [[id:1b12a8e0-16cf-4c0c-8f5b-c2b61443c16f][Perspective-n-Point]] algorithms.

2D image-based methods use 2D RGB images. Multiple images are rendered by
projecting the existing 3D model from various angles, and then establishing
2D-3D correspondences.

3D point-cloud-based methods use 3D geometric descriptors for matching.

* Template-based methods

Template-based methods find the most similar template from the templates labeled
with ground truth 6D object poses.

* Voting-based methods

Each pixel or 3D point can contribute to the 6D object pose estimation by
providing one or more votes.


* Method comparison

The different methods have their own trade-offs. When the target object has rich
texture or geometric details, template based methods are a good choice. When
there exist occlusions such as in cluttered scenes, correspondence-based or
voting-based methods perform better than template-based methods, since template
methods highly depend on global features extracted, while the former two methods
use local information.
