:PROPERTIES:
:ID:       0e10abd0-015f-4478-9a46-802d3c39aacc
:END:
#+title: Critical Thinking

* Introduction
Critical thinking is reasonable and reflective thinking focused on
deciding what to believe or do.

Ideal critical thinkers are disposed to:

1. Care that their beliefs be true, and their decisions be justified
   1. Seek alternate hypotheses and explanations
   2. Consider seriously other points of view
   3. Try to be well informed
2. Care to understand and present a position honestly and clearly.
   1. Discover and listen to others' view and reasons
   2. Be clear about the intended meaning of what is said
   3. Determine and focus on the conclusion or question
   4. Seek and offer reasons
   5. Take into account the total situation
   6. Be reflectively aware of basic beliefs
3. Care about every person
   1. Avoid intimidating or confusing others, account for others'
      feelings and level of understanding
 
Critical thinkers are able to do the following:

1. Focus on a question
2. Analyze arguments
3. Ask and answer clarification or challenge questions
4. Judge the credibility of a source
5. Observe and judge observation reports
6. Deduce and judge deduction
7. Make material inferences
   1. To generalizations, and explanatory hypotheses
8. Make and judge value judgments
9. Define terms and judge definitions, using appropriate criteria
10. Attribute unstated assumptions that belong under both basic
    clarification and inference
11. Consider and reason from premises
12. Integrate the dispositions in making and defending a decision
13. Be sensitive to feelings, level of knowledge and degree of
    sophistication of others
14. Employ appropriate rhetorical strategies, reacting to fallacy
    labels in an appropriate manner.

* Meta-cognitive Terms
- A posteriori :: Latin for reasoning or deductions made from known
                  facts or established knowledge that is not a
                  prediction or a hypothesis. Can also be used as an
                  adjective "a posterior knowledge", meaning knowledge
                  that is dependent on evidence or fact that has
                  already been established.
- A priori :: Latin for reasoning or deductions made without the need
              for known facts or knowledge, that is can be a
              hypothesis or prediction, e.g. stangelets are an example
              of a priori reasoning. Can also be used as an adjective
              “a priori knowledge”, meaning a claim that is true
              without having to be backed by empirical evidence, e.g.
              all bachelors are unmarried.
- Abductive Reasoning :: One of three types of reasoning, the others
     being the more familiar deductive and inductive reasoning. It has
     been described as reason that is most likely to lead to a
     conclusion because it deals with a subject or knowledge that is
     complete as not all the facts can be proven. It has been called
     the type of reasoning that requires a leap of faith.
- Alternative Views :: This is another interpretation of the same set
     of facts or points of information.
- Analysis :: How information has been dissected to give meaning, e.g.
              data analysis. This is the paramount indication of
              critical thinking. It is the cognitive process of
              “identifying the intended and actual inferential
              relationships among statements, questions, concepts…or
              other forms of representation intended to express
              beliefs, judgments…information, or opinions.”
- Anecdotal Evidence ::  Proof which is possibly only true for some
     specific instances, not necessarily for all instances. Proof that
     may not necessarily be replicated by formal experiment.
- Appeal :: An appeal is a technical term for a rhetorical device used
            to make an argument more persuasive. Some forms of
            persuasion are listed below, as can be seen some are more
            rational than others. When unmasking assumptions and
            evaluating arguments, attention should be paid to the type
            of appeal being made and whether it is ethical in the
            context, e.g. an appeal to emotion to raise money may or
            may not be ethical depending on what pressure is being
            applied to the emotion of the audience.
  - Appeal to Authority :: This is an attempt to persuade an audience
       that something is correct and should be accepted because it is
       endorsed by an authority or an organization with a reputation
       for good governance.
  - Appeal to Celebrity/Fashion :: This is an attempt to persuade is
       made to the audience’s desire to emulate or be like a famous
       person or to follow the latest social trend, fashion here
       refers to more than clothes, it may also refer to taking
       selfies at graduation ceremonies because many people did so
       this year.
- Appeal to Emotion :: This persuasive technique plays on an
     audience’s feelings, it uses the Aristotelean notion of pathos.
     Its use may be valid e.g. in a court case to ask for clemency for
     a pregnant murderer not be executed before her baby is born,
     since the baby is innocent of the crime. An appeal to emotion may
     be suspect when it is used to make an audience feel they are
     lacking if they do not care about a particular issue, e.g. in an
     advertisement to allow methadone to be sold as a heroine
     substitute in mainstream pharmacists.
- Appeal to Identity :: This persuasive technique works on an
     audience’s sense of group versus self-identity, e.g. “Count on
     me, Singapore”, “We are Singapore”, “Home” and other National Day
     Parade songs work on national identity.
- Appeal To Logic/Reason :: This persuasive technique relies on the use of
     logic or a systematic set of propositions in order to convince
     the audience of the credibility of the argument. It uses the
     Aristotelean notion of logos, and is seen as the strongest form
     of persuasion and therefore also argument. This persuasive
     technique lends itself to technological and scientific arguments,
     but there may be flaws in an argument that entirely relies on
     logos, consider for instance, the sorts of argument that would
     have had to be debated before the hydrogen bomb was dropped in
     Hiroshima.
- Appeal to Morality :: This persuasive technique works on the
     audience’s sense of what is right, moral, or ethical. It uses the
     Aristotelean notion of ethos, e.g. International pressure on
     Ukraine to give more access to the crash site of MH17 is based on
     an appeal to morality.
- Appeal to Popular Belief :: This persuades through asking the
     audience to consider some common value in humanity, or some
     belief that many people value, e.g. family values, a problem may
     arise when the definition of the key word, in this case “family”
     changes form one section of the population to another, such as
     traditional, blended and pink family values. An appeal to
     commonality works when there is a strong association between the
     audience and the issue at hand, e.g. environmental issues and a
     sustainable fishery idea.
- Appeal to Self-interest :: This persuasive technique leverages on
     Maslow’s hierarchy of needs to convince an audience that a
     specific course of action is for their own good, be it personal
     security, self-worth, fear of hunger etc. This is most often used
     in advertising, e.g. “Because you deserve it”.
- Argument :: Any text graphic, written or spoken that uses reasons
              to support the author’s position or point of view.
- Assertion :: Statements that are made without any supporting
               evidence of justification.
- Authorial bias :: The inclination or opinion that a writer or a
                    speaker has for a particular point of view.
- Authorial voice :: This is the opinion of the writer or the speaker,
     and not the writer or the speaker quoting from or referring to
     anyone else’s view. The authorial voice is important in any
     argument as it shows the author’s critical thinking value add.
- Bandwagon :: This term is a metaphor for those who agree or support
               a particular idea or campaign because it is fashionable
               or popular. These people are said to have “jumped onto
               the bandwagon” because they have supported something
               without knowing why they have done so. They have been
               caught up with the crowd.
- Bias :: Prejudice or propensity towards a particular view.
- Ceteris Paribus :: Latin for “all things being equal”. It is used as
     a condition to preface a statement. E.g. “Ceteris paribus the
     economy continues to grow at 5% annually, Nagaland will reach its
     projected sales target by 2015.”
- Claim :: A declarative (information giving) sentence which may be
           true or false. All arguments have claims, when analyzing
           arguments, the truth or otherwise of claims have to be
           assessed. Claim and declarative statements are also term in
           formal logic and C programming, but the definitions in
           there are different.
- Conclusion :: When writing or speaking, it is the natural or logical
                end point which all the reasons given in an argument
                lead to. It can also be a judgment or summative
                decision made after reading or listening to someone
                else’s argument.
- Construct an Argument :: This means putting together a thesis or
     hypothesis, a line of reason with a selection of reasons that
     develop or support the thesis or hypothesis and a robust analysis
     of the points of information,. All this leads to a warranted
     conclusion. There should be care to ensure there are no unfair
     instated assumptions, unwarranted inferences or fallacies in the
     reasons or the line of reasoning. Care must also be given the
     credibility of sources and the accuracy of data. The entire
     cognitive process should be expressed cogently, so for instance,
     care must be taken over word choice and expression of thought.
- Counter Argument :: This refers to an opposing viewpoint or an
     objection raised against a specific argument or claim.
- Deconstruct an Argument :: This means to take apart an argument in
     order to assess its component parts and then to evaluate the
     argument as a whole.
- Deductive Reasoning :: This is the type of reasoning that leads to a
     confirmed or guaranteed conclusion. This is because all the known
     facts are given or can be worked out. Mathematics is based
     largely on deductive reasoning. It also refers to the sort of
     line of reasoning in an argumentative essay where the author
     states the thesis at the start of the essay and then sets out
     his/her reasons and evidence in support of the thesis.
- Definition :: The meaning of a key word or phrase as used in an
                argument, which need not be the same as the dictionary
                meaning. But which has to be specified in the
                argument.
- Disposition :: Habit or attitude toward a trait of behavior. A
                 critical thinking disposition is specifically the use
                 of a self-regulatory systematic means to analyze
                 information. Such a disposition generally shows
                 diligence in seeking as much information as possible,
                 careful attention to detail, respect for the views of
                 others, consideration in the expressions of one’s own
                 stance, resilience in working out solutions and
                 open-mindedness.
- Double-speak :: Word or phrase that is deliberately unclear in
                  meaning, could be a political or military euphemism,
                  that is a nice sounding expression for something
                  that is actually unpleasant, e.g. “friendly fire”
                  and “collateral damage” – for being shot at by one’s
                  own side and being killed therefore by accident.
- Euphemism :: A word or phrase that is used to tactfully or politely
               refer to something unpleasant or socially taboo, e.g.
               “Sanitation engineer” instead of “rubbish man”. It is
               not usually meant to be deliberately deceiving unlike a
               double-speak expression.
- Evaluation :: Assessing the claims, assertions, opinions or other
                representations of an argument or idea. Evaluation
                necessitates identifying relevant points for the
                argument, credibility of sources, logical consistency,
                valid assumptions and appeals.
- Evidence :: Proof that supports a point or conclusion or line of
              argument. This may be data, observation, visual
              representation e.g. photographs or video, artefact, e.g.
              fossils, books, antiques etc.
- Explanation :: This is the process either written or spoken of
                 justifying or giving reasons for a belief or a
                 decision. This is the verbal representation of one’s
                 thought processes.
- Fact :: Proof that is based on something that can be proven by
          scientific experiment or replicating a social science
          experiment, or something which is true by popular
          observation e.g. the sun rises in the east and sets in the
          west.
- Fallacy :: An error in reasoning or a flaw or defect in a reason or
             a line of reasoning. It can also refer to an argument
             being entirely fallacious, e.g. the flat Earth theory was
             proven completely fallacious (adjective for fallacy),
             once space travel allowed Man to see the planet from
             above.
- False Logic :: This is where the propositions do not add up to a
                 conclusion as stated probably because the context is
                 not fully explained or some conditions are not met,
                 e.g. Birds have wings. Airplanes have wings.
                 Therefore airplanes are birds. False logic is also a
                 term in mathematics, Boolean logic and computer
                 science – but the definitions in those other subjects
                 are different.
- Generalization :: There are valid generalizations and invalid
                    generalizations. A valid generalization is an
                    overall statement describing a consistently
                    observed pattern or trend in data or some other
                    empirical evidence or social phenomenon. An
                    invalid generalization is a statement purporting
                    to describe a pattern or trend in data, other
                    empirical evidence or social phenomenon that is
                    based on insufficient sampling, lacking
                    confirmatory evidence or using anecdotal evidence.
                    Invalid generalizations contribute to a weak
                    argument.
- Habit of Mind :: Synonym for critical thinking disposition.
- Inductive Reasoning :: This is the type of reasoning that will give
     a conclusion that is probably valid. It also refers to the sort
     of line of reasoning in an argumentative essay where the author
     starts with a specific question, then builds up a line of
     reasoning that leads towards a conclusion.
- Inference :: Critical thinking skill used to identify the
               information that is most pertinent to drawing a
               reasonable conclusion, hypothesis, theory or educe
               consequences arising from data, evidence, principles,
               observations or other forms of representation of
               information or knowledge.
- Interpretation :: A specific person’s explanation of a phenomenon or
                    an event. Please see also ‘explanation”.
- Judicious :: Adjective to describe when good or sound judgment or
               reasoning is used. E.g. That argument used the data
               judiciously to support the inferences and conclusion;
               it did not make too big a claim
- Justification :: The explanation for holding a particular view.
- Line of reasoning :: This is the order in which the points selected
     to support an argument are arranged. The usual line of reasoning
     is that one point should lead into the next point and so build up
     a convincing case for the argument.
- Logical consistency :: This means that the points do not contradict
     each other within the argument. Also all the reasons support the
     conclusion.
- Man of straw :: This is a kind of fallacy in argumentation when an
                  author deliberately uses something that has been
                  distorted or represented absurdly and is thus easy
                  to refute in order to make his/her argument look
                  stronger, e.g. inventing a fictitious person and
                  story to illustrate a point, taking an opponents’
                  words out of context. C.f.
                  http://skepdic.com/refuge/ctlessons/lesson9.html. It
                  is sometimes referred to as Aunt Sally.
- Non sequitur :: Latin for “does not follow from”. Used to show that
                  one point is illogical following from the point
                  before.
- Open-minded :: This is an attitude or a disposition where one is at
                 least receptive to another point of view, and to be
                 willing if necessary to change one’s own view in the
                 light of convincing new evidence or better reasoning.
- Position :: A point of view supported by reasoning.
- Predicate :: The basis for which an argument is made, a technical term taken from formal logic.
- Premise :: Propositions used that are held to be true and used as a basis for an argument. E.g. Our premise that the rule of law is essential in human society means that law enforcement is integral part of any country.
- Prima Facie :: Latin term meaning “on the surface” or at face value.
- Propaganda :: Information that is transmitted by an organization or government to disseminate a particular view on a topic. This is usually persuasive in nature and is different from public education as it has a more subjective content.
- Proposition :: A statement that is presented as true as part of an argument. This may turn out to be false after evaluation, or less valid than originally presented.
- Public Education :: Information disseminated to inform the general
     population. Moe objective content than propaganda. E.g. a public
     education poster on wearing condoms to avoid STD is different to
     one that says having abortions is murder.
- Reasoning :: This is the process of thinking, also known as cognitive process.
- Reflection :: Thinking back to an action, event or a process to
                consider what lessons may be learned in order to make
                better progress. A critical thinking reflection is one
                in which one looks back on a specific action, event or
                process in a systematic way. Critical thinking
                practitioners have developed a few templates that
                others may use, or one can develop one’s own.
- Refutation :: In an argument, there is a claim which may be followed
                by a counter claim. The refutation is the counter
                claim to the counter claim that reinstates the
                validity of the original claim. E.g. Argument:
                Sustained silent reading is a good way of improving
                one’s language abilities in a language. Counter
                argument: However, does everyone have enough time to
                spend on sustained, silent reading every day?
                Refutation: Stephen Krashen (1982,) has shown that
                reading for as little as 25 minutes a day is
                sufficient to build up language skills over time. It’s
                a method in argumentation that allows the proposition
                to anticipate an objection and to refute it before the
                opposition does so. It strengthens the proposition’s
                stance.
- Self-regulation :: Synonym for self-discipline, but especially with
     regard to applying a critical thinking checklist to all
     information that needs to be processed.
- Stereotype :: This is related to a generalization. A stereotype is
                an unjustified conclusion or judgment about a specific
                group. That is an unwarranted conclusion, e.g. doctors
                are rich, Chinese mothers are tiger moms. Stereotypes
                give rise to weak arguments.
- Tautology :: Unnecessary repetition, the author makes the same point
               but may use different words. Repeating a point does not
               reinforce it in a logical way.
- Unstated Assumption :: This is a belief that the author of an
     argument assumes his/her audience shares. It is on this unstated
     assumption that the author rests his/her case. Unstated
     assumptions are valid if they are indeed commonly believed e.g.
     cultural assumption among members of the same culture, but they
     are not valid if only the author or a select group actually
     believes this, e.g. Libraries should have all sorts of books.
     Unstated assumptions are often found in propaganda pieces, but
     can also be found in most arguments. Most arguments following the
     western scientific model will have unstated assumptions about the
     conventions of good argument.
- Value Judgment :: The value that someone places on something, this
                    is essentially subjective. Consider this sentence:
                    “More works of Shakespeare are sold annually than
                    Jane Austen novels”. This is a statement of fact
                    and can be verified with sales figures. However,
                    “Jane Austen’s books are much easier to read and
                    are more enjoyable than Shakespeare’s plays.” This
                    is a value judgment because it is subjective.
- Weasel Words :: Words that make claims sound true but are actually
                  misleading or false. Weasel words are a sort of
                  fallacy, e.g. “many experts …” – this makes it look
                  as if something is endorsed by authorities in the
                  field, but is so vague that there is no possibility
                  of checking the credibility of sources. The use of
                  such words weakens an argument.

* Critical Thinking Components
1. Summary of specific information set
2. synthesis of relevant other information
3. CT Value add (analysis, hypothesis, counter argument, refutation,
   conclusion, application, inference)
4. nuanced language use
