:PROPERTIES:
:ROAM_REFS: [cite:@hoDetectingCharacterizingLateral2019]
:ID:       f9c73799-b36c-427b-a100-da4cb35b23ff
:END:
#+title: Ho, Cidon, Gavish, Schweighauser, Paxson, Savage, Voelker, Wagner :: Detecting and Characterizing Lateral Phishing at Scale

This is one of the first large-scale investigations into [[id:d5cd2a5a-739d-411b-a34e-f5cd9ff1176b][lateral phishing]] attacks.

Their dataset comprises of 113 million /sent/ emails, with a total 1902 lateral
phishing emails. Their data contains emails obtained via the Microsoft Office365
API: this means they have access to whatever the API provides (e.g. email
headers). These data also contained only lateral phishing attacks using
malicious URLs as their attack vectors.

The team had trained a random forest classifier on top of a few handcrafted
features to obtain suprisingly good results: their classifier has was able to
detect 87.3% of the attacks in the dataset, with only 4 false positives per
million emails.

Their classifier used 3 sets of features:

1. Capture that compromised account contacts many recipietns
   1. Number of unique recipients across email's to, cc and bcc headers
   2. Jaccard similarity of email's recipient set to historical recipients seen
      from the preceding month
2. Lure (E.g. vocab for document sharing)
   2. Boolean feature, if email contains any of the 150 of the most common words
      appearing in phishing attacks
3. Exploit (Attack vector)
   1. URL ranking

The authors observed that there were two main narratives for lateral attacks:

1. They use the pretext of sharing a document
2. They send a warning message about a problem with their account, calling for action
