:PROPERTIES:
:ID:       ea9dbdd4-cb1c-43bc-959f-afc2afc67b52
:ROAM_REFS: [cite:@ahrensHowTakeSmart2017]
:END:
#+title: How To Take Smart Notes

* Introduction to the Zettelkasten Method
:PROPERTIES:
:ID:       c9d33eae-6813-4712-825b-a44f050b2897
:END:

Luhmann used 2 slipboxes: a reference slip-box for collecting ideas about things
he has read, and an ideas slip-box containing only original, self-generated
content.

In the morning, Luhmann would take notes from his readings, penning them down
onto a piece of paper with a source inside. In the evening, he would go through
these notes and expand on them, writing about how they impact his current
studies.

Luhmann also kept an index into his system, referring to a few notes that serve
as an entry point into a line of thought or topic.

* Implementing the Zettelkasten
:PROPERTIES:
:ID:       8aaae80a-a751-4d8b-a32b-6779a1c33c38
:END:

To implement the Zettlekasten, one will need:

1. Something to quickly capture ideas. These captures are only temporary; they
   will be processed later into permanent notes.
2. A reference management system like Zotero. The system should allow notes to
   be linked to each reference.

* Arguments For Zettelkasten
:PROPERTIES:
:ID:       e5c45af0-4e7a-44f6-8303-c7d89364690f
:END:

1. Forces you to adopt a linking system: connect ideas, tangents
2. Break ideas up into smaller pieces, increase surface area for
   expansion

* Arguments Against Zettelkasten
:PROPERTIES:
:ID:       86945603-2d2f-4bba-9d52-ac80eb13a138
:END:

1. Densely interconnecting ideas across domains results in complex mental
   models, may obscure reality (Source:
   [[https://fs.blog/venkatesh-rao/][Venkatesh Rao, 2016 podcast with Farnam
   Street]])

* Book Notes
- You need something to capture ideas whenever and wherever they pop into your head.
- Focus on writing: rephrasing ideas into your own words, attending lectures with a clear purpose, focus on relevant aspects
- Standardize notes into the slipbox format, which can be understood without context
- Focus on what is interesting, let ideas accumulate and emerge without force
- academic writing is not a linear process
- Having frequent feedback loops helps learning
- Permanent notes must be written for an audience without context
- Reviewing is insufficient for learning, one learns best from elaboration
- The slip-box handles recall and information storage, while the brain is in charge of creative linking and understanding
- Read texts with questions in mind
- Writing with an eye towards existing notes allow us to take into account more information
- Elaborate on ideas in different contexts
- Forgetting is important -- so we can focus on what's currently important
- References between notes are much more important!
- Make keywords specific, with context e.g. capital allocation problem
- Comparing new notes with old notes help us discover differences and insight
- Permanent notes require thinking about what's relevant for long-term thinking and idea development
- Ask questions like "what's interesting?" and "why should I note this down?"
