:PROPERTIES:
:ID:       f7b36f1c-0cb9-494a-a6e7-4f5dacb26723
:END:
#+title: Negotiation

1. A good negotiator prepares, going in, to be ready for possible
   surprises; a great negotiator aims to use their skills to reveal
   the surprise they are certain to find
2. Don't commit assumptions; instead view them as hypotheses and use
   the negotiation to test them rigorously
3. People who view negotiation as a battle of arguments become
   overwhelmed by the voices in their head. Negotiation is not an act
   of battle; it's a process of discovery. The goal is to uncover as
   much information as possible.
4. To quiet the voices in your head, make your sole and
   all-encompassing focus the other person and what they have to say.
5. Slow. It. Down. If we're in too much of a hurry, people feel as if
   they're not being heard.
6. Put a smile on your face. When people are in a positive frame of
   mind, they are more likely to collaborate and problem-solve.
7. Use voice inflections appropriately:
   1. The late-night DJ voice: Inflect your voice downward, keeping it
      calm and slow. This creates an aura of authority and trustworthiness.
   2. The positive/playful voice: This should be the default voice.
      Maintain a light and encouraging attitude.
   3. The assertive voice: Used rarely.
8. Mirrors: Repeat the last three words of what someone has just said.
   This insinuates similarity, which facilitates bonding. It
   encourages the other side to empathise and bond with you.
9. Tactical Empathy: By acknowledging negative feelings and the other
   person's situation, you immediately convey that you are listening.
10. Focus on clearing the barriers to agreement. Do an accusation
    audit: get barriers and negative influences into the open
11. Pause. After you label a barrier or mirror a statement, the
    counterpart will fill the silence.
12. Label your counterpart's fears to diffuse their power.
13. List the worst things that the other party could say about you and
    say them before the other person can.
14. Remember you're dealing with a person who wants to be appreciated
    and understood. Use labels to reinforce and and encourage positive
    perceptions and dynamics.
15. Break the habit of getting people to say "yes". Being pushed for
    yes makes people defensive.
16. "No" is not a failure. "No" often means "wait", or "I'm not
    comfortable with that". It is the start of a negotiation, not the end.
17. "Yes" is the final goal of a negotiation, but don't aim for it at
    the start.
18. Saying "No" makes the speaker feel safe, secure and in control.
    Your counterpart defines their space and gains the confidence and
    the comfort to listen to you. "Is now a bad time to talk?" is
    always better than "Do you have a few minutes to talk?"
19. Sometimes the only way to get your counterpart to listen and
    engage with you is by forcing them into a "No". This means
    intentionally mislabeling one of their emotions or desires or
    asking a ridiculous question.
20. Negotiate in their word. Don't beat them with logic. Ask them
    questions that open paths to your goals.
21. If a potential business partner is ignoring you, contact with a
    clear and concise "No"-oriented question.
22. Creating unconditional positive regard opens the door to changing
    thoughts and behaviours. Humans have an innate urge toward
    socially constructive behaviour. The more a person feels
    understood, the more likely that urge for constructive behaviour
    will take hold.
23. "That's right" is better than "yes". Reaching "that's right" in a
    negotiation creates breakthroughs.
24. Use a summary to trigger a "that's right". The building blocks of
    a good summary are a label combined with paraphrasing. Identify,
    re-articulate, and emotionally affirm the world according to your
    counterpart.
25. All negotiations are defined by a network of underlying desires
    and needs.
26. Meeting halfway often leads to bad deals for both sides.
27. Approaching deadlines entice people to rush the negotiating
    process and do impulsive things that are against their best
    interests.
28. The word "fair" is an emotional term people usually exploit to put
    the other side on the negative and gain concessions. Don't get
    suckered into a concession, always ask why.
29. You can bend your counterpart's reality by anchoring his starting
    point. Before you make an offer, emotionally anchor them by saying
    how bad it will be. Set an extreme anchor to make your "real"
    offer seem reasonable, or use a range to seem less aggressive.
30. People will take more risks to avoid a loss than to realize a
    gain. Make sure your counterpart sees that there is something to
    lose with inaction.
31. The listener is the one in control of the conversation.
32. Don't try to force your opponent to admit that you are right.
    Aggressive confrontation is the enemy of constructive negotiation.
33. Avoid questions that can be answered with "yes" or tiny pieces of
    information. These inspire the human need for reciprocity; you
    will be expected to give something back.
34. Ask calibrated questios that start with the words "how" or "what".
    Give your counterpart the illusion of control, inspire them to
    speak at length, revealing important information.
35. Don't ask questions that start with "why" unless you want your
    counterpart to defend a goal that serves you.
36. Calibrate your questions to point your counterpart toward solving
    your problem. This will encourage them to expend their energy on
    devising a solution.
37. Asking calibrated "how" questions keep your counterpart engaged
    but off-balance. Answering the questions give your counterpart the
    illusion of control.
38. Use "how" questions to shape the negotiating environment. Get your
    counterpart searching for solutions to your problem.
39. Don't just pay attention to the people you're negotiating with
    directly; always identify the motivations of the player's behind
    the scenes.
40. Follow the 7-38-55 percent rule by paying close attention to tone
    of voice and body language. Incongruence between words and
    non-verbal signs will show when your counterpart is lying or
    uncomfortable with a deal.
41. Is the "Yes" real or counterfeit? Test with the rule of three: use
    calibrated questions, summaries and labels to get your counterpart
    to reaffirm their agreement at least three times.
42. A person's use of pronouns offers deep insights into their
    relative authority. If you're hearing a lot of "my", "I", the real
    power to decide probably lies elsewhere. Picking up a lot of "we",
    "they", it's more likely you're dealing with a savvy decision
    maker with their options open.
43. Use your own name to make yourself a real person to the other
    side, and even get your own personal discount.
44. Identify your counterpart's negotiating style: accomodator,
    analyst, or assertive

* References
- Never Split the Difference
