:PROPERTIES:
:ID:       4151d751-762b-4c4c-b457-cec74a475210
:END:
#+title: SAID Principle

The SAID principle states that the body makes specific adaptations the body
makes specific adaptations to the demands you place on it. Your body builds
strength and flexibility where demand is placed on it, and loses strength and
flexibility when no stressors are applied.

This principle is used in building "good" [[id:4e31cb8d-f49c-4131-9a07-8e6dce8860d3][posture]]: the body's current posture is
an adaptation to the current stressors being placed on it: slouching over the
chair is the postural configuration that requires the body to exert the least
effort when working. The body simply needs to be constantly moving in all
healthy ranges of motion, applying stress there, to maintain a healthy state.

This principle is also used in [[id:d1474eff-9e13-4eff-a792-1855a6ca322f][running]]. Understanding what tissues are being
stressed, and the amount of time it takes for the body to condition to stress is
important to safe and effective training. To avoid overstress, we maintain a
stress table that catalogues the body's condition over time, understanding how
various factors (such as sleep) affect stress.
