:PROPERTIES:
:ID:       c9a04aac-d9a2-4c15-994c-4863d0aa7a0a
:ROAM_REFS: https://www.goodreads.com/book/show/28256439-the-hidden-life-of-trees
:END:
#+title: The Hidden Life of Trees: What They Feel, How They Communicate

- author :: Peter Wohlleben
- Goodreads :: https://www.goodreads.com/book/show/28256439-the-hidden-life-of-trees

* Themes
- [[id:43d5b868-8202-462c-bca0-ec67e0fc43a6][Wood Wide Web]]

* Interesting Facts

- Some forests plan reproduction in advance, such as birch trees. This regulates
  many things, for example, the population of animals that depend on their
  fruit.
- Parent trees enforce a strict upbringing on the new generation of young
  seedlings. One way they do this is through light deprivation: young seedlings
  are short and covered by the crowns of the parent trees. The young trees often
  only receive enough light to survive, enforcing a slow growth, and encouraging
  them to develop extensive branches and leaves that can absorb the little
  sunlight they receive. Once the mother tree perishes, the young trees can then
  grow up strong.
- "A tree is only as strong as the forest": Trees are social beings, and trees
  try to ensure that every tree in the forest is equally successful (e.g. their
  photosynthesis rate is often synchronized). 
- The notion of having to space out the vegetation to avoid overcrowding comes
  from a forester's mentality. In practice, trees don't practice this sort of
  distancing.
