:PROPERTIES:
:ID:       3e6df0fa-ce24-4ab0-b063-a0627f364796
:END:
#+title: The Fermi Estimate

Physicist Enrico Fermi was a master at guesstimation. Consider questions like
these: What's the size of the market for razors in China? How many piano tuners
are there in Chicago? These questions are called Fermi problems.

#+begin_quote
It is better to be approximately right, than precisely wrong
#+end_quote

Fermi tackles this problem by breaking down the problem, and performing
back-of-envelope calculations. We tackle the problem of estimating the number of
piano tuners in the city of Chicago. What numbers do we need to know?

1. The number of people in Chicago
2. The number of people who play the piano in Chicago
3. The number of music schools in Chicago
4. How often a piano needs to be tuned
5. How long it takes to tune a piano

Often, getting an estimate within a factor of 10 or 20 is enough to make a
decision.

* Resources
- [[https://www.lesswrong.com/posts/PsEppdvgRisz5xAHG/fermi-estimates][Fermi Estimates - LessWrong]]
