:PROPERTIES:
:ID:       08836b31-8abc-425b-b633-f20ced532825
:END:
#+title: The Distressed Debt Cycle

Investors buy debt securities because they expect to be paid interest
periodically and have their principal repaid when the debt matures.

However, for distressed debt, the consensus is that this debt may not be repaid.
The motivation behind purchasing the debt is then to have a "creditor claim"
against the debtor: when the company declares bankruptcy, they gain ownership of
the company, depending on the debt held. A distressed debt investor tries to
figure out what a bankrupt company is worth, how this value will be divided
amongst creditors, and how long this process will take.

As with other cycles ([[id:83ec5164-9a32-4baa-bdb7-c5850c3a0b0c][The Economic Cycle]], [[id:db19c192-25e2-4273-91d2-f9bb7975afba][The Credit Cycle]], [[id:414fc43d-9699-4c96-8d76-1c36fc2cb7af][The Profit Cycle]])
the ability to obtain top returns from distressed debt is cyclical, and
dependent on these other cycles.

Opportunities to make returns here are created by the *unwise extension of
credit*. Here's an example with bonds:


- Stringent standards are applied to bonds
- This facilitates the servicing of debt, making defaulting scarce
- Having a combination of high yields and low risk makes bonds attractive,
  attracting capital to the bond market
- Increased capital translates to increased demand, resulting in increased bond
  issuance
- Larger amounts of bond issued leads to lowering of standards

Influences from other cycles include:

- A slowing economy affects investor psychology, company profitability ([[id:414fc43d-9699-4c96-8d76-1c36fc2cb7af][The
  Profit Cycle]]), and fluctuation in the credit market ([[id:db19c192-25e2-4273-91d2-f9bb7975afba][The Credit Cycle]])
- [[id:db19c192-25e2-4273-91d2-f9bb7975afba][The Credit Cycle]] affects the availability of capital to refinance debt
