:PROPERTIES:
:ID:       db19c192-25e2-4273-91d2-f9bb7975afba
:END:
#+title: The Credit Cycle

The credit cycle refers to the changes in the availability of credit or capital.
This is one of the most volative cycles than has a fundamental influence on the
economy. The credit window can go from open to shut in an instant. Why is credit
so important?

1. Credit is required to refinance maturing debt: companies and other economic
   units usually don't pay off their debts, but roll them over
2. Capital is an essential ingredient in the productive process, and is required
   to finance growth

A closed credit market causes fear to spread, often out of proportion to
reality. Difficult conditions can cause the vicious cycles of closing and fear,
leading to financial crises.

** How does the credit cycle work?
:PROPERTIES:
:ID:       edd9051e-cf17-4324-80e4-a37a0718616d
:END:

1. The economy prospers
2. Providers of capital thrive, increasing their capital base
3. The scarcity of bad news results in perceived lowered risks in investing and lending
4. Risk averseness lowers
5. Financial institutions expand their business, providing more capital
6. Financial institutions compete for market share by lowering demanded returns
   (e.g. cutting interest rates), lowering credit standards, and providing more
   capital per transaction
7. Capital is destroyed: investments are made in projects where the cost of
   capital outweights the returns (if any)
8. Losses cause lenders to be discouraged
9. Risk averseness rises, and with it interest rates and restrictions
10. Less capital is available, and only to the most qualified of borrowers
11. Companies are starved for capital, unable to roll over debts and default
12. This causes economic contraction
