:PROPERTIES:
:ID:       800fbd66-d32d-45ea-adbc-73d55658afff
:END:
#+title: A Complete Workflow in Emacs

Org-mode provides incredibly good tooling for note-taking. It has:

- Now in-built citation support with ~org-cite~ ([[https://blog.tecosaur.com/tmio/2021-07-31-citations.html][introducing citations!]])
- Jupyter-like capabilities via ~org-babel~, supporting notes in the form of
  literate programming
- In-built latex support
- Support for capturing snippets at any moment

Together, these [[id:8aaae80a-a751-4d8b-a32b-6779a1c33c38][provide a strong basis]] for implementing the Zettelkasten. All
that is left is providing a streamlined workflow.

* In the Zettelkasten, Less is More

Other note-taking tools seem to always be introducing new features (Roam,
Obsidian, Logseq). The slipbox as Luhmann implements it is simple, and I believe
simplicity is a key feature of the slipbox. Ensuring that there is no feature
creep prevents complexity from creeping into the note-taking workflow, and a
simple workflow allows the focus to be on the notes themselves.

* Not everything needs to be done in Emacs

- Flashcards for when not at computer (Anki)
