(TeX-add-style-hook
 "rl"
 (lambda ()
   (LaTeX-add-bibitems
    "sutton2000policy"
    "mnih16_async_method_deep_reinf_learn"
    "gu16_q_prop"
    "Mnih_2015"
    "schaul15_prior_exper_replay"
    "schulman15_high_dimen_contin_contr_using"
    "dann2017unifying"
    "kaelbling1996reinforcement"
    "jin_q_learning_provably_efficient"
    "mnih2013playing"
    "van2016deep"
    "anschel2017averaged"
    "andrychowicz2017hindsight"
    "dabney2018distributional"
    "schultz97_neural_subst_predic_rewar"
    "stolle2002learning"
    "haan19_causal_confus_imitat_learn"
    "levine18_reinf_learn_contr_as_probab_infer"
    "abbeel2004apprenticeship"
    "ratliff2006maximum"
    "ziebart2008_maxentrl"
    "pmlr-v70-haarnoja17a"
    "rusu15_polic_distil"))
 :bibtex)

