:PROPERTIES:
:ID:       934898c7-9e49-4f62-8acf-ba1bc39dfad6
:END:
#+title: Applying Forecasting in Finance

The success of an investment is dependent on four tasks:

1. Detecting causal patterns in a noisy world
2. Making well-calibrated probabilistic forecasts about how these patterns will
   play out in the future
3. Factoring these forecasts into investment decisions that deliver risk-adjusted returns
4. Conducting post-mortems on investment failures and successes to make
   increasingly accurate forecasts and better trades

One classic challenge is determining the role of good luck and managerial skill
in portfolio performance. Traditional methods either:

1. Collect and observe data over many years. This is to allow for stable
   statistical estimates. However, this process takes time.
2. A second method is to use case-study post-mortems, which rely on accurate
   causal inferences.

Cerniglia and Tetlock propose using the Alpha-Brier system to disentangle skill
from luck quicker [cite:@cernigliaAcceleratingLearningActive2019]. This system
requires firms to first construct an analytical infrastructure that allows them
to capture in real-time the accuracy of forecasting judgments underlying
investment decisions. The Alpha-Brier process also facilitates learning by
giving investors the explicit accuracy feedback they need for making
well-calibrated forecasts on the drivers of market outcomes.
