#+SETUPFILE:./hugo_setup.org
#+HUGO_SECTION: books
#+TITLE: Are We Smart Enough to Know How Smart Animals Are? 

- title :: Are We Smart Enough to Know How Smart Animals Are? 
- author :: Frans de Waal
- personal rating :: 4/5
- tags :: [[file:books.org][§books]]

Why is it that facial expression is universally consistent?

* Language As Root Of Thought

If language were at the root of thought, why is it that we sometimes
find ourselves at a loss for words?

Language is one of the distinguishing features of the human species.
Other species are able to exhibit similar or higher levels of
cognitive function without an equally powerful language.

As humans, we are able to use language to communicate ideas that
transcend time, and this has been essential for our survival.

* The Social Brain Hypothesis

The intelligence required to effectively deal with social networks may
explain why the primate order underwent its remarkable brain
expansion.

* Consciousness

There is claim that humans are the only species that consciously
access the past and the future, but recent evidence shows otherwise.
Either animals also posses consciousness, or consciousness is not a
necessary ingredient for such introspection.

* Names

Some species like dolphins use /signature whistles/, which is
analogous to human names.

* Studying cognition

Neuroscience may tell us where things happen in the brain, but does
not help us formulate new theories or design insightful tests of
cognition. 

Instead of making humanity the measure of most things, we need to
evaluate other species for what they are.

