:PROPERTIES:
:ID:       74238f6a-c29c-465f-871d-d32d551a50fe
:END:
#+title: Arguments Against Bayesian Inference

- tags :: [[id:06635cd6-7ae1-4ba0-b82f-5a344871d94e][Bayesian Inference]]

Whereas frequentist methods derive solutions via inventing estimators
(a multitude of them may exist) and computing a likelihood function,
Bayesian methods only offer one answer to a well-posed problem.

The Bayesian inference method is conditioned on assumptions (for
example, the prior). Some say the prior introduces subjectivity. *But
how can one make inferences without assumptions?* Bayesian methods
force us to make these assumptions /explicit/.

Once the assumptions are made, the inferences are objective, unique,
and can be agreed upon by everyone. These assumptions are easy to
modify, and we can quantify the sensitivity of our inferences to our
assumptions. It also quantifies the uncertainty in our inferences.

There is a common misconception that the aim of inference is to find
the most probable explanation for some data. While the most probable
explanation may be of some interest, this is only the peak of a
probability distribution, and it is the whole distribution of
explanations itself that is of interest. /The most probable outcome
from a source is often not a typical outcome from that source./
