#+setupfile: ./hugo_setup.org
#+title: ARM Assembly Programming

- tags :: [[file:operating_systems.org][Operating Systems]], [[file:prog_lang.org][Programming Languages]]

* Background

In a /machine language/, instructions are encoded as 0's and 1's. This
is unwieldy for programmers  to write. Hence, to tell processors what
to execute, programmers use an /assembly language/, writing these
instructions in textual form, for example:

#+begin_src text
  MOV R9, R3
#+end_src


An /assembler/ translates the assembly language into machine language.

There are many machine languages, each designed with a processor in
mind, enabling fast and simple circuits to be built to execute the
instructions. Each machine language requires a corresponding assembly
language, since the assembly language must support a different set of
machine instructions. The design of the machine language encoding is
called the /instruction set architecture (ISA)/.

* Memory Organization

- Byte-addressable, 32-bit address space
- little- or big-endian addressable
- 32-bit word length
- word, half-word and byte data transfers to and from processor registers
- word and half-world transfers must be aligned

* Arm 


