:PROPERTIES:
:ID:       0176818a-61d9-45a3-92f1-c3ec59e426a1
:END:
#+title: Capitalism

Capitalism is an economic system characterized by a particular combination of
institutions. These institutions put in place different sets of laws and social
customs regulating the production and distribution of goods and services in an
economy.

Key economic institutions include /private property/ (people owning things),
/markets/ (where goods could be bought and sold) and /governments/ (institutions
controlling production and distribution). Societies with governments that take
on this role are called centrally-planned economies.

Markets are a means of transferring goods or services from one person to
another. In most markets, the transfers are voluntary: transfers are mutually
beneficial.

/Firms/ consist of one or more individuals, owning a set of capital goods used
in production. The firms pay wages and salaries to employees. The goods and
services are properties of the owners of the firm, and the owners sell the goods
and services on markets to make profit.

The rise of capitalism vastly improved living standards, for several reasons:

- technology :: competing firms resulted in strong incentives to develop and
  adopt new technology, and to invest in capital goods that would have been
  beyond the reach of small-scale family enterprises
- specialization :: workers specialized in the tasks they performed, resulting
  in increased labour productivity. Specialization can only occur when a person
  is able to obtain the goods and services they need by other means.

Hence, markets have allowed cooperation on a global scale. On the other hand,
market competition provides a mechanism for weeding out those who under-perform.
Capitalism is the first economic system in which membership of the elite often
depends on a high level of economic performance.

Capitalism is supported by:

1. Private incentives for cost-reducing innovation
2. Firms with proven ability to produce goods at low cost
3. Public policy, for the production of essential goods and services that would
   not be provided by private firms
4. A stable society
