:PROPERTIES:
:ID:       31ff2b41-5b94-41aa-b17b-76cc050dbe81
:END:
#+title: Evolving Spiking Neural Networks

Early evolving [[id:54691107-81a0-4d7b-8c51-d8a74bde7f86][Spiking Neural Networks]] architectures use the [[id:a22d942d-8772-43d9-b956-6aebae0e8913][Leaky
Integrate-And-Fire]] model, and rank-order encoding. eSNNs can be used for
classification. Given an input sample, the spike train is propagated through the
SNN, resulting in the firing of output neurons. If no output neuron is
activated, the classification result is undetermined. If one or more output
neurons emit a spike, the label of the neuron with the shortest response time
represents the classification result.

* Training an eSNN

For each class label an individual repository is evolved. A new output
neuron is created and fully connected to the previous layer of
neurons. Input spikes are propagated through the network, and the
weight vector for the neuron is computed, along with its firing
threshold. This weight vector is compared to existing neurons in the
repository. If neurons are too similar (e.g. small Euclidean distance
between weight vectors), they are merged.

See cite:schliebs13_evolv_spikin_neural_networ_survey for a
comprehensive review.

bibliography:biblio.bib
