:PROPERTIES:
:ID:       2a96393b-15af-43d6-8f65-cdb7e69b33bf
:END:
#+title: Fitness

* Posture

Your current posture is the result of your body's adaptations to the
demands you place on it. Your body builds strength and flexibility
where demaind is placed on it, and loses strength and flexibility when
no stressors are applied.

The factors that lead to increased incidence of back pain are
decreased muscle endurance and weakness rather than structural
factors.

The key to resolving pain and discomfort is improving strength and
endurance of the appropriate musculature.

** Understanding Pain

One of the first models of pain was the gate ocntrol theory. This
quickly became outdated, and 2 primary models remain: The neuromatrix
theory of pain, and the biopsychosocial model.

The biopsychosocial model of pain asserts that there are biological,
psychological and social factors that influence pain within the body.

- biological factors :: pain from repetitive stress, trauma, damage
- psychological factors :: effect of emotions and thoughts, mood, attention, sleep etc.
- social factors :: Social activities, work and occupation resulting in more isolation

The neuromatrix model looks at six areas, namely:

- cognitive issues :: memories of past experiences
- sensory issues :: nociceptive inputs from cutaneous, visceral and musculature senses
- emotional issues :: limbic system and stress mechanism
- pain perception :: sensory, affectieve and cognitive dimensions
- actions :: voluntary and involuntary actions
- stress ::  immune system, cortisol, and other stress hormones

Pain is a protective mechanism, not necessarily a symptom of damage.
Not avoiding various activities due to pain, and not changing your
lifestyle around the pain are critical during a rehabilitation
process.


The three most common causes of tightness in the back are pain,
instability, or weakness. Your muscles may become tight to protect you
from injury. Exercises that are aimed at strengthening and stabilizing
the back tend to clear up such instances of back pain and tightness.

** Posture in real life

Posture is a very complex interplay between the neurological and
musculoskeletal systems within the body, which all come together to
make up a specific position.

Aligning the joints into a better position would allow more muscular
force to be used, yielding both improved performance, and less risk of
injury.

We need to think about posture in the context of moving well, and the
ability to adapt effectively to your environment while avoiding
injury-prone positioning.

** Correcting Posture

Consistent effort, over time, is one of the cornerstones of physical
change, and everything you can do to encourage this is beneficial.

Upper Crossed Syndrome (UCS) and Lower Crossed Syndrome (LCS)
describes patterns of weakness and tightness in the upper and lower
body respectively, in the common desk job culture.

UCS: Head-forward posture: weak neck flexors, weak scapular
retractors, tight upper cervical muscles/suboccipitals, tight chest
pec/pec minor/rounded shoulders

LCS: Anterior pelvic tilt: weak glutes, weak abs, tight hip flexors,
tight back

These are symptoms of the underlying cause. Any stretching and
exercise is like a bandage. It will help cover a wound and protect it,
but the real healing comes from your body engaging in the healing
process. Mindfulness and sustained habits that aid this process are
key.

** Corrective Exercises

Mobility and stability exercises improve your range of motion through
either dynamic movement or static holds. The strength and endurance
movements contribute most to your ability to maintain good postural
positioning in your daily activities.
