:PROPERTIES:
:ID:       04af721e-9cee-4a00-a426-baec803b108c
:END:
#+title: Gaussian Filter

Gaussian Filters is a tractable implementation of the Bayes filter
([[id:155935aa-af99-4629-b232-dfa0b48ad239][Bayes Filter]]) for continuous spaces.

* Key Idea

Beliefs are represented by a multi-variate normal distribution.

\begin{equation}
  p(x) = \text{det}(2 \pi \Sigma)^{-\frac{1}{2}} \text{exp} \left( -
    \frac{1}{2} (x -\mu)^T \Sigma^{-1} (x- \mu) \right)
\end{equation}

The density of variable $x$ is characterized by mean $\mu$ and
covariance $\Sigma$.

* Ramifications

Since beliefs are represented by a multi-variate normal distribution,
this means that beliefs are *uni-modal*. This is suitable for many
tracking problems. However, this is a poor match for many global
estimation problems with multiple hypotheses that should give rise to
their own modes in the posterior. 

* Representations

- moments representation :: The Gaussian is represented by its mean
  and covariance (first and second moments)
- canonical representation :: 

These representations have a bijective mapping, and are functionally
equivalent, but give rise to different algorithms.

Using the moments representation gives rise to the [[id:f34829e1-86aa-4700-8c42-474ab7c24620][Kalman Filter]].
