:PROPERTIES:
:ID:       09c3f011-7a51-4bf7-b65d-f7576abe077b
:END:
#+title: Singapore Society

* Introduction to Sociology
** Sociological Perspective
 Defined as seeing the general in the particular
  - Child birth: Education, use of contraception
  - Suicide: Strength of social ties vs individualistic societies
** Global Perspective
 Study of the larger world and our society's place in it. Logical extension of sociological perspective.
  1. High-income countries: 64 nations, including USA.
     These generate the majority of goods and services, people here own the most wealth.
  2. Middle-income countries: 73 nations
     People as likely to live in rural villages as developed countries. Considerable social inequality.
  3. Low-income countries: 57 nations
     Low standards of living. Majority struggle to get by: hunger, unsafe water etc.

 Why we care:
 - Where we live shapes the lives we lead
 - Societies globally become increasingly interconnected
*** Benefits of the sociological perspective
 - Assesses the truth of common sense
 - Helps us see opportunities and constraints in our lives
 - Empowers us to be active participants in our society
 - Helps us live in a diverse world
*** Origins of sociology
 Changes in Europe during 18th nadn 19th century:
 1. Factory-based economy
 Workers becoming part of an anonymous labour force, weakening traditions that had guided community life.

 2. Growth of cities
 "Enclosure movement": fencing off of areas for diferent purposes. Social problems such as air pollution.

 1. Political changes
 New ways of thinking: Hobbes, Adam Smith and John Locke.
 Philosophers now spoke of things like /personal liberty/ and /individual rights/.

 August Comte coined the term /sociology/ in 1838, and saw it as a product of 3 phases:
 1. Theological
 Religious view that society expressed God's will
 2. Metaphysical (Renaissance: 15th Century)
 Society was a natural rather than supernatural phenomenon
 3. Scientific
 Rise of science, headed by Newton, Einstein and other scientists.
 Scientific approach used to analyze society.

 Positivism: Use of "positive" facts as opposed to mere speculation
*** Sociological Theory
 Translating observations into understanding
 Theory: Statement of how and why specific facts are related
 Three theoretical approaches
**** Structural-Functional Approach
 Framework for building the theory that sees society as a complex system whose parts work together to promote solidarity and stability.
 Social structure: any stable societal pattern.
 Analyze these structures and their consequences for the operation of society as a whole.
 Robert K Merton distinguished between:
 1. Manifest functions: recognized and intended consequences of social patterns
 2. Latent functions: unrecognized and unintended consequences

 Social dysfunction: social patterns that disrupt the operation of society
**** Social-conflict approach
 Framework for building the theory that sees society as an arena of inequality that generates conflict and change.
 Used to reason about social/wealth/racial inequality etc.
**** Gender-conflict approach
 Feminism, gender inequaltiy
**** Race-conflict approach
 POV that focuses on inequality and conflict between people of different racial and ethnical categories
**** Symbolic-interaction approach
 Framework for building the theory that sees society as a product of the everyday interactions of individuals
 We live in a world of symbols, and attach meaning to everything

 Summary in last two pages of reading week 1
** History in Singapore
 - PAP hostile towards history in 1960s and 1970s. 
 - ‘Before you discuss your future,’ Lee Kuan Yew exhorted the citizens of
 Singapore in 1998, ‘remember how we got here.’
 - nostalgia for the 1970s was an inherent criticism of the fast pace of change and goals of the state.
 - PAP's rule under threat: but capitalized it, harnessing history for nationalist aims
 - History is a trope of knowledge, an established way of thinking about society and as such is critical to understanding a society.
 - The failure of Singaporean society to theorize, or come to terms with, its own past, constitutes opaqueness in the study of Singapore.
*** Singaporean Histography
 - First written by colonizers
   - Sir Thomas Stanford Raffles(1781 - 1826) autobiography: /A memoir of the Life of and Public Service of Sir Thomas Stanford Raffles/. Published 1824.
   - Expansion of historical work happened closer to national independence (around 1960s)
   - Similar to HK, where waning of colonialism results in the exploration of their history.
*** Elite Representations
 - Large part of Singapore's history told in terms of the life of LKY.
 - Texts are attempts to build a "national mythology", conflates national history with personal.
 - Biography and autobiography provide an incomplete picture of a national history.
 - Political biographies and autobiographies of LKY reinforce the national narrative.
 - Inclusion in national education curriculum
 - The function of Lee’s autobiographies is broader than the writing of a national narrative, because the autobiography actively participates in the construction of a national imaginary.
 - 'Even from my sick bed, even if you are going to lower me into the grave and I feel that something is going wrong, I will get up.' - LKY
 - Lee is very much a product of colonialism, educated in a British tradition. He is often described as ‘a Chinese mirror of the perfect Anglo leader’.
 - S Rajaratnam and Devan Nair "midwives of the Singaporean nation-state". Set the template for writing of history in the future.
 - Nair
   - Looking to the past for inspiration was both dangerous and backward.
   - Industrialization/modernization divided people into those who look to the past and those who look to the future.
 - Sourcing for historical material is hard: bias, difficulty of dating pre-colonial material.
 - Censorship by Singapore Government
 - Low profile makes it hard to attract academics to work in historiography
 - The way in which a nation constructs its history can be integral to the construction of the nation itself. 78 The relationship between history and the nation in Singapore is polemical because of the state’s changing attitude towards the past.
 - Rajaratnam’s 1970s statement that ‘knowing where you are going is more important than knowing where you came from,’ 79 and Lee Kuan Yew’s aforementioned proclamation of 1998, ‘Before you discuss your future, remember how we got here’
 - Education policies concerned with mother-tongue language learning and the inclusion of Confucian values in the moral education curriculum are part of this desire to cultivate Singapore as an inherently ‘Asian’ nation.
 - Threat and struggle are the two dominant themes the PAP promotes in its understanding of Singapore’s history, and events and issues are manipulated to fit with this model
*** Nostalgia
 Rather than censoring such responses, the Singaporean state responded to the rise in nostalgia by trying to co-opt it for nationalist purposes. In
 transforming nostalgia from something that could potentially undermine the policies and rhetoric of development, to a positive part of a broader and
 multilayered nation building project, the state is acting in a typically adaptive mode. In mainstreaming nostalgia, the state effectively moved nostalgia away from the 1970s and broadened its meaning.
  ‘Friends and Family: A Singapore Album collection’ is both a virtual interactive web-based exhibition and a traditional museum exhibition. Encouraged to contribute to the collective Singaporean Identity
*** Summary
 With numerous strategies the Singaporean state attempts to control the meaning of history in Singapore. The past is presented by methods of display, content and absences, as uncontested and unproblematic. The historiography mirrors this. The history that the state constructs and manipulates ratifies the construction of cultural knowledge in Singapore, even when it is authored by. The more active role Singaporeans are playing as creators of historical knowledge has returned Singapore to a more traditional relationship with history. That is, the state is utilizing history as a form of nation building and as a way of negotiating a multiracial society. Instead of history presenting a threat to the fragile balance of a multiracial society, it is now a tool for bringing people together. In the shared experience of life in Singapore as well as the shared experiences of lives—births, marriages, celebrations, etc.—history has become a part of the national story. The state has been effective in widening the focus of nostalgia beyond the dangerous period of the 1970s, but as with other actions of adaptive regimes, as more is given to citizens the greater their potential demands become, and the greater the need for adaptation. In attempting to focus attention towards sites of nostalgia that are less problematic, especially the physical manifestation of buildings, the Singaporean state is still seeking to control the meaning of the past. An emphasis on heritage and the built environment freezes a historical moment and strips it of context. That is, the state is making heritage an object of the present and not the past. Likewise, ‘A Singapore Album’ and blog sites turn nostalgia into something that is contemporary not historical. In so doing the Singaporean state is simultaneously negotiating the production of historical knowledge and seeking to de-politicise history. If, as L. P. Hartley suggested ‘the past is a foreign country,’ 121 then making the past the present makes it less foreign.
* What is Singapore society?
** Defining Characteristics
*** Pragmatic
- National Education (NE) and Social Studies textbooks
- Emphasis of several core values and recurring themes

* What do you know of Singapore's history and manner which it is presented?
* National Society of Singapore (NSS)
** Concept of Resistance
Ho (2002) Internet as the guidance
** Gestural Politics
Goh Chok Tong: political scientists started talking about GP
Just trying to project a liberal image
maintain power relations (keep the people happy), prevent regression
to oppressive society

Lee (2008) : How the state uses rhetoric ("openness", "inclusiveness")
as liberal gestures 
They are gestures because words lack substance
"Civic" vs "civil": Duties vs rights
** Background
- NGO, non-profit
- Mission: promote nature awareness and appreciation
- 1986: MNS:S discovered area around Sungei Buloh
- MNS-S prepared its first conservation proposal
- State planned for an agro-technology park in the area
- 1989: Sungei Buloh Nature park was founded

Sungei Buloh isolated success

Government planned to build a golf course at Lower Pierce Reservoir,
which was ultimately void

25,000 strong petition could not change decision to build housing area

2011, Bukit Brown cemetery. 8-lane highway to be constructed
diagonally across the Bukit Brown cemetery
- Economic Pragmatism vs Conservation
* Gestural Politics
(Rodan 2006)
- Promises of openness does not amount to democratic developments
- Define the parameters of politics and political participation in
  Singapore under LHL's charge.
  - mediate the meanings of political transformation in Singapore via
    creative institutional and gestural initiatives.
- Goh Chok Tong promised a kinder and gentler style of rule when he
  took office in 1990.
- "liberal gestures" continue to reproduce and mediate an illiberal regime.
- Goh's rule as prime minister (from 1990 to 2004) arguably became
  best known for the institution and entrenchment of the infamous
  out-of-bound markers
  - Golfing terminology intended to demarcate the parameters of
    political debate and dissent in Singapore
  - OB markers remain the most cited reason for political apathy among
    its citizens and the corresponding lack of public discourse on
    civil society and political issues in SG.
- PM Lee's decleration of greater openness under his premiership could
  be seen as the continuation of PAP's "regime reproduction"
  initiatives that are intended to steer "change in Singapore down a
  preferred path of /political co-option/ rather than /political contestation/".
- Speech peppered with "openness" nothing more than a public relations
  statement to project Singapore as a mature, progressive and creative
  society to the rest of the world.
- display of readiness to engage with "diverse views"
- LHL's rule since August 2004 typified by use of language and
  buzzwords that "seem long on rhetoric  but short on content"
- "openness" and "inclusiveness" are terms that can be invoked
  repetitively and as liberally as desired.
** Examples
1. 9 March 2004, Singapore Tourism Board (STB) launched "Uniquely
   Singapore"
   1. Comprising a range of media advertisements for different global markets
   2. Developed in the wake of SG's recovery from its economically
      crippling encounter with the Severe Acute Respiratory Syndrome (SARS).
   3. Coincided with the circulation of broad rhetoric that speaks of
      a "more open" and "creative" Singapore.
   4. Vibrant place where locals and foreign talents can "live, work
      and play"
   5. Time Magazine, 1999, Singapore as "competitive, creative, even
      funky"; such inscriptions mark a form of radicalness that is
      intended to displace old mindsets about Singapore's colorless
      cultural landscape.
2. Fashionable rhetoric of "creativity", popularized by the Singapore
   government's decleration in 2002 that it would embrace the global
   "creative industries" project.
   1. overarching intention of creativity and innovation is to boost
      Singapore's economic capital by attracting talented individuals
   2. Productive energies of such "bohemian-creative" individuals
      would "rub off" on Singaporean workers.
3. Publicized changes have included:
   1. a declared willingness to appoint openly gay public servants to
      sensitive positions in civil service 
   2. Legalization of "bar-top" dancing in pubs and nightclubs
   3. Granting of permits for extreme sports such as skydiving
4. 2003, government has been busy liberalizing the city's nocturnal
   entertainment scene by allowing 24-hour "party zones" in night
   spots, along with a host of established hotels and clubs
5. Tolerance to difference, diversity and "acceptance" of alternative lifestyles
   1. LHL - panoramic vision of Singapore included "an expanded space"
      for Singaporeans to "live, laugh, grow and be themselves".
   2. Dimension and make-up of newly liberated space (like the
      invisible boundaries of the OB-markers), are likely to remain
      cryptic and ambiguous
   3. Policy changes affect minority of Singaporeans, but give PAP
      enough substance to push their "rhetoric"
6. "Great Casino Debate"
   1. Under GCT's rule, proposals for a casino in Singapore have been
      rejected since the 1970s
   2. Pushing for casino not straightforward, necessary to engage the
      citizenry by gathering feedback and guaging opinions
   3. 13 march 2004, Singapore's Trade and Industry Minister George
      Yeo delcared Singapore's new state of openness when he said in
      Parliament that the government would "/keep an open mind/" on
      whether to build a casino in Singapore.
   4. Religious groups dismayed at proposal, voiced strong objections
   5. Group of citizens calling themselves "Families Against the
      Casino Threat in Singapore" (FACTS)
   6. FACTS collected 20000 signatures through an Internet petition,
      to be submitted to President of Singapore.
   7. Most believed debate amounted to nothing but talkfest
   8. By Dec 2004, MTI received more than 700 letters, emails and
      faxes on the issue
* Race
** Demographics
- Chinese 74.1%, Malays 13.4%, Indians 9.2%, Others (3.3%) - Singapore Census 2010
- CMIO classification
** Race as Colonial Legacy
- Singapore is a product of Western colonial capitalism
The idea of meritocracy is never enforceable in practice beacuse
social advantage is not equally distributed
** Cultural Logic of SG's Multiracialism
1. Heightened racial consciousness
2. Stereotypical thinking to reinforce racial differences
3. Top-down 
* Lecture Summary
** Lecture 1 Topic: Introduction - Studying Singapore Society
*** Knowledge production and dissemination
 Given that we are social actors born in a specific socio-political and
 historical context, we tap upon a range of sources of knowledge when
 we attempt to explain social issues or phenomena (e.g. low fertility
 rates; academic underperformance; etc.) These can be organised broadly
 as lay perspectives; and disciplined perspectives. However, there are
 approaches which are regarded more dominant than others. We considered
 how and why a particular perspective may emerge as dominant in a
 particular context and the key stakeholders interested in sustaining
 such dominance.
*** Disciplined perspectives and the sociological imagination
 To understand Singapore society beyond lay perspectives and the
 “commonsense”, the lecture introduced the framework of the
 “sociological imagination” (C.W. Mills). This broadly means we are
 able to go beyond the individual and connect “private” troubles to
 “public” issues (By extension, it is a quality of mind in making the
 connection between individual and society; biography and history; and
 self and the world.

*** The global perspective
 The global condition is an extension of the sociological imagination,
 which is important in view of the connectedness our lives to the world
 and the global structures that govern our lives.
*** Blaming the victim
 Therefore, when we extend our analysis beyond the individual and look
 toward more holistic and long-term systemic conditions to explain
 specific social phenomena, we move away from a limiting approach which
 solely “blames the victim” (Ryan).

** Lecture 2 Topic: Histories and the Past

*** Representations and politics of “the past”
 Our lecture stressed that we are not overly preoccupied whether the
 past (both pre-colonial and colonial) is historically “accurate” or
 otherwise, but rather how particular narratives of the “past” have
 been represented as dominant. Therefore, the lecture also considered
 who produces history (the “authors”) and its relationship to power,
 ideology and the state. In other words, these narratives are produced
 to reinforce specific interests of groups who control power and
 resources.

*** Historical consciousness
 The engagement of “historical consciousness” directs our attention to
 focus on the multiplicity of interpretations of “the past” to push the
 boundaries of historical knowledge. This means moving beyond history
 as a tool for propaganda to appreciate historical complexities and
 diversity/pluralism.

** Lecture 3 Topic: State and Civil Society
*** Civil society and citizen participation
 Our lecture attempted to critically analyse the extent to which active
 citizenship engagement on a range of different issues (e.g. the
 environment, women’s issues, LGBT and human rights, migrant workers,
 etc.) is rendered possible in Singapore. We differentiated between
 “civic” and “civil” society, and closely interrogated the role of the
 state in establishing legal, social and cultural boundaries pertaining
 to citizen participation.
*** Gestural politics and “resistance”
 We also closely discussed the relevance of Lee’s concept of “gestural
 politics” in which he refers as essentially “pseudo-politics”
 primarily aimed at sustaining the appearance of a liberal democracy
 while simultaneously extending the power of the authoritarian state
 through legal and extra-legal mechanisms, despite calls to
 “inclusiveness” and active citizenship.

 Globalisation and the internet: The final part of the lecture
 emphasised the role of the internet and transnational alliances with
 civil society organisations beyond Singapore in an attempt to not only
 increase its reach to a wider audience, but more crucially to
 strengthen the authority and legitimacy of the different claims local
 civil society organisations were making.

** Lecture 5 Topic: Race and Ethnic Relations
*** Race and ethnicity as socially constructed categories
 Our lectures made the distinction between race (perceived
 physical/genetic attributes considered socially significant to a
 collective) and ethnicity (perceived cultural attributes and practices
 rendered salient to a group). The lecture further demonstrated how
 race and ethnicity are not fixed or immutable categories, but rather
 how the meanings of such categories are very much dependent on the
 context and temporal dimensions (In the case of Singapore, the lecture
 showed the role of colonialism and how this shaped our understanding
 of ‘race’ in Singapore). At the same time, the lecture addressed how
 these markers were not inherently ‘natural’ especially given the fact
 that ‘race’ as a category has been disputed by scientists. Rather,
 these markers only carried weight and significance when specific
 groups ascribe these physical and/or cultural markers as important.
*** Prejudice and discrimination  
 At the same time, we also made an important distinction between
 prejudice (rigid and unfair cognitive attitudes and emotions about a
 category of people) and discrimination (unfair and unequal treatment,
 behaviour, action and practice enacted against a category of people).
*** Privilege and access to resources
 The lecture emphasised the importance of group membership and how
 these are linked to the allocation of rights, privileges, obligations
 as well as sanctions and disadvantages. These very much pertain to how
 race and ethnicity are employed as organising principles to govern
 social relations and the distribution of resources.
*** The politics of “difference”
 Our lecture then focused on how the state in Singapore makes sense of
 difference, how such differences include “race” and the broader
 implications of such differences. We attempted to explain how “race”
 has been defined by the Singapore state, why “race” has been so
 prominent and salient in Singapore, and how these have configured
 different dimensions of our social life.
*** Multiculturalism and difference
 We interrogated how the management of such differences has been
 translated into multiculturalist state policies and programmes that
 included housing, political representation and education. The lecture
 explained the different dimensions of multiculturalism which included
 the accordance of “equality” to each community and other principles.
 At a more critical level and through different areas of social and
 political life in Singapore, we appraised the implications, problems
 and contradictions embedded in the ideology of multiculturalism,
 particularly in relation to resource allocation, life chances and
 experiences of everyday racisms.
*** “Racial harmony” as repressive 
 The lectures finally appraised how multiculturalism provides the state
 the legitimacy to regulate and police race and ethnicity. We further
 interrogated how the discourse of “racial harmony” has been
 politicised to legitimise and reproduce state power and intervention,
 as well as the allocation and distribution of specific rights,
 privileges and resources.
 
** Lecture 6 Topic: Gender and Sexuality

*** Unpacking key concepts  
 In this lecture, we made the distinction between “sex” (biological and
 physical distinctions between male and female) and “gender” (socially
 and culturally produced differences between men and women). We also
 explained three other important concepts central to our lecture:
 sexuality; patriarchy; and heteronormativity. Membership in these
 group categories of sex/gender and sexuality are pertinent, given that
 these are tied to privileges, rights and resource allocation. These
 therefore revisit the primary topic of this section which addresses
 social inequalities.
*** State patriarchy and policy-making    
 The second part of the lectures addressed the issue of gender
 inequalities and analysed the social, economic, and political
 conditions in Singapore which facilitated the ‘naturalisation’ of
 dominant gender norms, values, and practices privileging male
 experiences. These included our critical appraisal of population and
 family policies, and political representation.
*** Sexuality and heteronormative interests 
 The final part of the lecture critically discussed the inequalities
 premised on differences of sexuality and the social implications of
 invoking heteronormative discourses pertaining to “conservatism”,
 which again legitimises a particular configuration of the patriarchal
 and heteronormative familial form as well as acceptable and
 permissible gender and sexual behaviour, which at a broader level, is
 in line with the state’s economic and productivist interests. The
 concept of sexual citizenship was explained to bring to the forefront
 again questions of rights and privileges of sexual minorities; as well
 as issues pertaining to belonging and emotional attachment to the
 nation-state.

** Lecture 7 Topic: Class and Meritocracy 

*** Social stratification and meritocracy
 In this lecture, we attempted to explain meritocracy as a system of
 stratification and rewards grounded on the basis of merit and
 non-discrimination (ethnicity, gender, sexuality, family, etc.). We
 discussed the key characteristics of meritocracy and how such a system
 which has been institutionalised and normalised in Singapore has
 shaped different dimensions in Singapore society. These include the
 fields of education and politics. We further appraised the challenges
 and contradictions in the ideology of meritocracy and unpacked the
 impetus of the ruling elite to sustain such an ideology, especially in
 relation to the justification of the given distribution of resources,
 rights and rewards. These also obscure how life chances and success
 are intimately shaped and connected to cultural capital, social
 connections, and other considerations. The lectures show further how
 the potentially egalitarian characteristics of meritocracy may clash
 with its emphasis on talent allocation, competition and reward,
 thereby transforming this into an ideology of elitism and inequality.
*** Class inequalities and the politics of welfare
 The lectures addressed the implications of widening income disparities
 and class inequalities. These were connected to provisions have been
 organised along racial self-help groups and away from state welfare,
 and the consequences and problems of such a system that has been
 institutionalised in Singapore. These have been rationalised to steer
 attention away from an overdependence on the state for help and
 obscuring inequalities which have been produced through widening
 income gap and other state policies.
*** “Blaming the victim”   
 We also demonstrated how the ideology of meritocracy takes attention
 away from structural conditions and the role of the state in
 allocating resources, placing the onus of accountability to the
 individual instead. At the same time, the repetition of meritocracy
 denounces the presence of discrimination, arguing that success and
 failure are contingent on the basis of merit.

** Lecture 8 Topic: Religion and Secularisation
*** Unpacking key concepts  
 In this lecture, we attempted to conceptualise “religion” by using
 functional definitions (what religion does) and substantive
 definitions (what religion is); as well as introduce the concept of
 “living religions” in Singapore.
*** Living religions and mixing-and-matching
 The second part of the lectures elaborated on the concept of “living
 religions” and outlined the religious landscape in Singapore. The
 focus of living religions stresses on the level of religious practice
 and everyday religiosity. We employed the case study of Hinduism to
 further show how living religions may not necessarily fit within
 strict frames of religious behaviour. We used the concept of
 “mixing-and-matching” (process of selecting and enacting different
 styles of religiosity preferred by a practitioner without these
 traditions merging and becoming a unitary whole).
*** Secularisation as a process 
 In our lecture, we first discussed the characteristics and processes
 involved in secularisation and to critically assess whether the
 separation between religion and politics was possible, especially
 during occasions where religious beliefs and practice contravene
 national interests and security. In this section we focused on the
 role of the state, state intervention and religion in Singapore; and
 the implications of possible competing interests between religious
 adherents/practitioners and the state.
** Lecture 10 Topic: Population and Health
*** Population and the “demographic crisis”
The lecture first considered the broader global and local conditions
that organised health care provision and financing in Singapore. These
included the dominant patterns in population affecting Singapore –
large ageing population, low fertility rates, high old-age dependency
ratio, increased morbidity and life expectancy, rise of chronic
illnesses, and wider income disparities and inequalities, contributing
to escalating health care costs.
*** Health System in Singapore
We subsequently examined the different principles structuring the
health care system and policies in Singapore (both in terms of health
care financing and coverage) and critically appraised the shortcomings
of health care in Singapore. These can be categorised as ‘spectacular’
and ‘systemic’ failures, based on the prescribed reading.

*** Vulnerable groups and the politicisation of health care
At the same time, we identified several groups which may be more
vulnerable than others such as HIV patients – as well as the problems
these groups potentially faced. The provision of health care
infrastructure to its citizens is also intimately tied to broader
state interests and legitimacy to rule the nation.

** Lecture 11 Topic: Popular Culture and the Arts
*** The power of the state and the arts
The lecture primarily outlined the relationship between the state,
popular culture and the arts, as well as the contesting visions and
interests of the state pertaining to the arts (instrumental, pragmatic
and political gains), as compared to the interests of arts
practitioners.

*** Cultural hegemony
We introduced and applied the concept of “cultural hegemony” and its
different dimensions to demonstrate how the ruling elites have been
able to naturalise a set of dominant ideas, beliefs and practices as
“universal” and “normal”. These ideologies can be potentially conveyed
through popular culture and the arts.

*** Ideology and resistance
Different forms of popular culture (films, TV, music, plays, etc.) can
be readily appropriated by the state to normalise state ideologies
such as multiculturalism and meritocracy, but at the same time such
forms can also be deployed by producers of popular culture and the
arts to critically respond to issues and problems in Singapore
society.

** Lecture 12 Topic: Migration and Globalisation
*** Migrant workers in Singapore:
In our lecture, we screened the film “Ilo Ilo” which allows us to
recalibrate our understanding of migrant workers in our everyday
lives. At the same time, the film also afforded us glimpses to
extrapolate relevant concepts we have employed in our module
pertaining to the meanings of difference and its concomitant
privileges, rights and access to resources; as well as concepts such
as prejudice, discrimination, power and inequality embedded through
race/ethnicity, class and gender as organising principles.
*** State regulation of migrant workers 
In the next and final lecture (Week 13), it will briefly contextualise
and elaborate the position of migrant workers as reflected in the
film, how categories of migrants are established (foreign “worker” vs.
foreign “talent”) and the implications of these distinctions in a
“global city” like Singapore.
