:PROPERTIES:
:ID:       9904c5cb-25ac-4a8f-8173-7109c4102aca
:END:
#+hugo_slug: grasp_estimation
#+title: Grasp Estimation

Grasp estimation is the task of estimating the 6D gripper pose in camera
coordinates. Grasps can be categorized into the 2D planar grasp, or the 6DoF
grasp. For 2D planar grasps, the grasp is constrained from one direction, so the
6D gripper pose can be simplified into a 3D representation, which includes the
2D in-plane position and 1D rotation angle. For 6DoF grasps the gripper can
grasp the object from various angles.

* Evaluating Grasp Contact Points

The first category of methods sample candidate grasp contact points, and use
analytical methods or deep learning methods to evaluate the quality of the
grasp. This relies on prior knowledge such as object geometry and physics
models. [[id:e0dc9aa5-d8d5-44d4-b0f9-490839667b61][mahler_dex-net_2017: Dex-Net 2.0: Deep Learning to Plan Robust Grasps
with Synthetic Point Clouds and Analytic Grasp Metrics]] uses deep learning
methods to plan grasps.

Other methods such as in cite:morrisonClosingLoopRobotic2018 generate pixel-wise
grasp affordance maps

bibliography:biblio.bib
