:PROPERTIES:
:ID:       ed6e0839-d3e7-46ef-a856-2e9a4d0d9970
:END:
#+hugo_slug: learning_how_to_do_hard_things
#+roam_key: cite:maciver_hard_things
#+title: Learning How To Do Hard Things

- tags :: [[id:54c22d91-285c-4dd4-835c-9fc737534cc9][Learning]]
- paper :: cite:maciver_hard_things

The key is to isolate one aspect of the problem that is difficult and
work on it. This provides a direct feedback loop.

#+begin_quote
 1. Find something that is like the hard thing but is easy.
 2. Modify the easy thing so that it is like the hard thing in exactly one way that you find hard.
 3. Do the modified thing until it is no longer hard.
 4. If you get stuck, do one of the following:
    1.  Go back to step 3 and pick a different way in which the problem is hard.
    2.  Recursively apply the general system for learning to do hard things to the thing you’re stuck on.
    3.  Go ask an expert or a rubber duck for advice.
    4.  If you’re still stuck after trying the first three, it’s possible that you may have hit some sort of natural difficulty limit and may not be able to make progress. 
 5. If the original hard thing is now easy, you’re done. If not, go back to step 2.
#+end_quote

bibliography:biblio.bib
