:PROPERTIES:
:ID:       5643d617-aa4e-4d67-86b0-bfe25d6c2929
:END:
#+title: nasarGrandPursuitStory2011: Grand pursuit: The story of economic genius
#+roam_key: cite:nasarGrandPursuitStory2011

* Grand pursuit: The story of economic genius
  :PROPERTIES:
  :Custom_ID: nasarGrandPursuitStory2011
  :URL:
  :AUTHOR: Nasar, S.
  :NOTER_DOCUMENT: /home/jethro/Dropbox/Calibre/Sylvia Nasar/Grand Pursuit (213)/Grand Pursuit - Sylvia Nasar.epub
  :NOTER_PAGE: (15 . 80884)
  :END:
** Before 1870 economics was mostly about what you couldn’t do. After 1870, it was mostly about what you could do.
:PROPERTIES:
:NOTER_PAGE: (12 . 6314)
:END:
** “The desire to put mankind into the saddle is the mainspring of most economic study,” wrote Alfred Marshall, the father of modern economics.
:PROPERTIES:
:NOTER_PAGE: (12 . 6427)
:END:
** Malthus had concluded that the drive to reproduce trumped all other human instincts and abilities, including rationality, ingenuity, creativity, even religious belief.
:PROPERTIES:
:NOTER_PAGE: (14 . 4493)
:END:
** Marx shared Engels’s conviction of the utter hopelessness of reforming modern society, and the need to free Germany from God and traditional authority. Engels introduced him to the idea of the proletariat. Marx felt an immediate sense of identification with that class. He saw the proletariat not only, as one might expect, as the “naturally arising poor” but also as the “artificially impoverished . . . masses resulting from the drastic dissolution of society,
:PROPERTIES:
:NOTER_PAGE: (15 . 12012)
:END:
** Within two or three generations, the industrial revolution demonstrated that the wealth of a nation could grow by multiples rather than percentages
:PROPERTIES:
:NOTER_PAGE: (15 . 30016)
:END:
** While the Manifesto referred to “ever-decreasing wages” and “ever-increasing burden of toil” as matters of historical fact, in Das Kapital, Marx argued that the “law of capitalist accumulation” requires wages to fall, the length and intensity of the working day to rise, working conditions to deteriorate, the quality of goods consumed by workers to decline, and the average life span of workers to fall. He did not, however, fall back on the second of his arguments about ever-worsening depressions.
:PROPERTIES:
:NOTER_PAGE: (15 . 60457)
:END:
** the great twentieth-century economist John Maynard Keynes would dismiss Das Kapital as “an obsolete economic textbook which I know to be not only scientifically erroneous but without interest or application to the modern world.”
:PROPERTIES:
:NOTER_PAGE: (15 . 82533)
:END:
