#+title: Optionality

Optionality is the right, but not obligation, to take an action.

* Restrict Your Choices

Consumer capitalism is designed to give us the illusion of great choice, even
while it traps us within one narrow sector of possibilities.

By restricting your choices along one dimension, you can create more freedom
along a dimension that's more important to you. Example of choices to restrict
include:

1. The clothes your wear every day
2. The food you eat every day

* Generate Better Options

Generating better options is much more important than being a perfect
decision-maker. The single most important ways to open up options in life are
(a) having more money, and (b) requiring less of it. This is why frugality is so
important.

Money, however, is only valuable so long as it continues to open up options:
after some point, it isn't.

* Acting Dead

Frugality does not equate to acting dead.

Are you spending as little money as possible? Are you escaping work? These are
all things that your dead grandpa already has you beat. A good litmus test for
acting dead is inverting the advice, and see if it still sounds wise.

* Classifying Options

We can classify options based on their risk-reward ratio:

1. *Bottomless Pits of Doom*: High risk, low reward. E.g. driving motorcycles
   has little reward over cars, but the fatality rate is much higher
2. *Dead Ends*: Modest risk, modest reward. E.g. buying stocks. This leads to
   modest gains, in exchange for taking modest risk.
3. *Treasure Chests*: Low risk, high reward. E.g. scalable side-hustles: selling
   software over and over again with little marginal cost.
   
