#+title: Overcoming Setbacks in Life

* Questions to Ask Yourself When Something Bad Happens

1. Is this actually going to materially hurt me over a significant period of
   time? How much cash would I have paid to prevent it? If not a lot, maybe I
   shouldn’t be too upset.
2. Is there some hidden upside I haven’t noticed yet? How could this actually
   end up being beneficial?
3. Is this misfortune funny or ironic in some way? For example, is it either
   completely typical or totally unexpected in an amusing way? If I’m
   catastrophising, are my over-the-top misinterpretations of the situation
   themselves kind of funny? Would I see the funny side if it happened to a
   stranger?
4. Is this the kind of bad thing I should have anticipated, such that it should
   have already been built into how I feel about the world?
5. Could something even worse have happened that didn’t? Are there other people
   who’ve ended up even worse off than me, which make me look, if anything,
   lucky?
6. What unexpected good things have happened to me lately, that have offset my
   bad luck in this case?
7. What would I say to someone else if this happened to them? Presumably not “I
   suggest you… feel bad 👌”.
8. Do I endorse the idea that everyone in the world who encounters a situation
   of this kind should also be sad? If not, why should I be sad? I should not.
9. What can I learn from this situation that will make me better off by
   preventing the same, or worse, in future?
10. Is there any way I can get around or overcome this problem which actually
    won’t be so bad? If so, I should just do that.
11. Based on past experience, do I have the strength to get through this
    tragedy? Unless this is among the worst things in my life, the answer is
    almost certainly yes! Have I gotten through something similarly bad in the
    past? Again, almost certainly, yes! Am I still distressed by similar
    misfortunes from the past? Almost certainly not – in which case, why bother
    being distressed about this thing now?

* Questions to Ask When Someone Wrongs Me

1. Can I see a way that what they’ve done would have been reasonable from their point of view?
2. Is there any way of interpreting their behaviour that doesn’t imply that they
   were inconsiderate or mean-spirited? For example, maybe they didn’t know some
   relevant information, or foresee this outcome? Or just got unlucky? Yes
   people are dumb and make stupid mistakes. Shit happens. 🤷 Just get over it.
3. Has this person ever done any nice things for me that help to offset the harm they’ve done here?
4. Have I ever wronged someone similarly, by accident, or through selfishness?
   Yes. Is this person actually less considerate than me, all things considered?
   50/50 they aren’t.
5. If the above fails, can I just avoid this person in future, and pay them no
   further mind? Hopefully! In which case, problem solved and I can move on.

* Sources
- [[https://80000hours.org/2018/12/dealing-with-setbacks/][A Simple Checklist For Overcoming Life and Career Setbacks]]
