#+SETUPFILE:./hugo_setup.org
#+TITLE: PARA Method

PARA is a method of organising digital information, designed by Tiago
Forte. Tiago Forte also proposed the method of [[file:progressive_summarization.org][§progressive_summarization]].

PARA stands for:

- project :: a series of tasks linked to a goal. E.g. app mockups,
  project plans, blog post etc.
- areas :: a sphere of activity with a standard to be maintained over
  time. E.g. Health, Finances, Travel, Hobbies
- resources :: a topic or theme of ongoing interest. E.g. habit
  formation, project management, interior design
- archive :: inactive items from the above 3 categories

* Projects vs Areas

Projects always have a goal to be achieved, typically with some hard
deadline. The end of a project is signalled by the occurrence of some
discrete event. 

Areas are ongoing standards, that may have no end date or eventual
outcome. *Projects always fall into areas*.

* Why distinguishing projects and areas is important

This helps someone *understand the true extent of their commitments*.
Commitments are towards projects -- responsibilities with tangible
outcomes. Knowing how projects connect to your long-term goals (areas)
is important.

* Contrasting with [[file:zettelkasten.org][§zettelkasten]]

This seems to be in contrast with other techniques like [[file:zettelkasten.org][§zettelkasten]],
which propose no such organization, instead using links between
different information.

My personal thoughts:
1. PARA looks like it would form a good hierarchical overview of tasks
   and information. Zettelkasten does not provide this.
2. Zettelkasten still remains a useful tool for low-level,
   inter-project information-linking.

* Resources
- [[https://praxis.fortelabs.co/the-p-a-r-a-method-a-universal-system-for-organizing-digital-information-75a9da8bfb37/][The PARA Method: A Universal System for Organizing Digital Information | Praxis]]
