:PROPERTIES:
:ID:       6216e0a9-f46a-4bb7-9d8a-a463c7d5e86e
:END:
#+title: PARA Method

PARA is a method of organizing digital information, designed by Tiago
Forte. Tiago Forte also proposed the method of [[id:6adf5333-604c-49ec-bf27-4585d870aa5b][Progressive Summarization]].

PARA stands for:

- project :: a series of tasks linked to a goal. E.g. app mockups,
  project plans, blog post etc.
- areas :: a sphere of activity with a standard to be maintained over
  time. E.g. Health, Finances, Travel, Hobbies
- resources :: a topic or theme of ongoing interest. E.g. habit
  formation, project management, interior design
- archive :: inactive items from the above 3 categories

* Projects vs Areas

Projects always have a goal to be achieved, typically with some hard
deadline. The end of a project is signalled by the occurrence of some
discrete event. 

Areas are ongoing standards, that may have no end date or eventual
outcome. *Projects always fall into areas*.

* Why distinguishing projects and areas is important

This helps someone *understand the true extent of their commitments*.
Commitments are towards projects -- responsibilities with tangible
outcomes. Knowing how projects connect to your long-term goals (areas)
is important.

* Contrasting with [[id:c178794c-78d1-459d-9725-15f2f6cd970a][Zettelkasten]]

This seems to be in contrast with other techniques like [[id:c178794c-78d1-459d-9725-15f2f6cd970a][Zettelkasten]].
which propose no such organization, instead using links between
different information.

My personal thoughts:

1. PARA looks like it would form a good hierarchical overview of tasks
   and information. Zettelkasten does not provide this.
2. Zettelkasten remains a useful tool for low-level,
   inter-project information-linking.

* Resources
- [[https://praxis.fortelabs.co/the-p-a-r-a-method-a-universal-system-for-organizing-digital-information-75a9da8bfb37/][The PARA Method: A Universal System for Organizing Digital Information | Praxis]]
