:PROPERTIES:
:ID:       6ec6e356-ac36-42ba-bc81-60a918e3f355
:END:
#+roam_key: http://michaelnielsen.org/blog/principles-of-effective-research/
#+title: Principles of Effective Research | Michael Nielsen

- source :: http://michaelnielsen.org/blog/principles-of-effective-research/
- author :: [[id:3652626a-b6f0-41e9-9e12-ea6e028edc93][Michael Nielsen]]
- tags :: [[id:63384aa8-5da8-41c5-96aa-17f7925c274f][Research]]

#+begin_quote
“We are what we repeatedly do. Excellence, then, is not an act but a habit.”  -- Aristotle
#+end_quote

/The foundation of effective research is a strong motivation or desire to do
research./ Motivation and desire, however, is insufficient. One needs to be
healthy, have fun, and spend quality time doing other things.

* Aspects of Personal Behaviour

1. A strong vision of what you want to achieve
2. Work proactively towards the vision
3. Take personal responsibility for successes and failures

Develop disciplined work habits, and achieve balance between self-development
and the actual creative research process.

Vision is not something you develop overnight. The vision informs your everyday
and every week decisions, giving you a genuinely exciting goal to work towards.

Self-discipline requires clarity in what you want to achieve, and how yo u go
about achieving it. A social environment that encourages the development of
research skills and excellence is important.

* Aspects of Research

People who concentrate mostly on self-development usually make earl y exits in
their research careers. The academic systems ensures that the failure to churn
out good research is recognized, and consequently have trouble finding jobs.

Early on in the research career, there are many advantages to publishing a lot
of papers. It gives the opportunity to learn to write and communicate well.
However, the long-term costs are significant.

* Staying Current ([[id:f35e7982-2d31-4e06-845a-62d588dd27c8][Reading]])

1. Quickly skim a great deal of work, to keep track of what is known, what sort
   of problems people are thinking about
2. Pick a dozen or so papers each year to read deeply, in the belief that they
   contain the most important results of the year.

* Research Styles

Different people have different styles of creative work. There are two different
styles: problem-solver and problem-creator, that may be useful ways of thinking.

- problem-solver :: a person who works intensively on a well-posed
  problem
- problem-creator :: a person who writes simple papers, but asks
  interesting questions, or pose problems in a new way

** Problem-creator

Problem-solvers have social advantages in research, and are more common.
However, there is a sizeable comparative advantage being a problem-creator. To
be a good problem creator, one must:

1. Develop a taste for what's important
2. Know the internal and external standards for what is important
3. Always be exploring for problems
   1. Problems should be well-posed, or able to be well-posed after some work
   2. Fall within a reasonable time
   3. Be above some minimum threshold of interest and difficulty
4. Be ahead of the game
5. Identify the messes. What's currently difficult to understand?

** Problem-solver

1. Have clarity, goals, and forward-momentum
2. Multiple formulations
3. Spontaneous discovery as the outcome of self-development
4. Work on important problems, but not all the time.
   1. Small problems help maintain momentum, keep morale high.
