:PROPERTIES:
:ID:       f35e7982-2d31-4e06-845a-62d588dd27c8
:END:
#+title: Reading and Writing Inbox
#+todo: TO-READ READING WRITING | DONE

This is a list of articles or books that I found interesting at some point in
time. Not all of them will be read: this is both impossible and unlikely. Some,
I will read in more detail, and others, I will read shallowly and refile
somewhere else.

To engage with the content I'm reading, rather than simply making annotations on
the content, I will also process the ideas presented into [[id:e377ddf7-edc9-4f2a-9fa6-4f8842c426eb][evergreen notes]]. The
workflow is something like this.

1. Read the piece of content, and make annotations on it (with [[https://hypothes.is/][Hypothes.is]]).
   These annotations go into a writing inbox.
2. When I'm done with reading, take a look at the corresponding writing inbox,
   and process them into [[id:e377ddf7-edc9-4f2a-9fa6-4f8842c426eb][evergreen notes]]. Mark annotations as processed once
   they are done, clearing the writing inbox.
3. Mark the piece of content as done.

* The List
** TO-READ [[https://thinkingthrough.substack.com/p/context-switching-cost-more-than][Context switching costs more than we give it credit for. - Thinking Through]] :productivity:
** TO-READ [[https://notes.andymatuschak.org/Evergreen_notes?stackedNotes=z3PBVkZ2SvsAgFXkjHsycBeyS6Cw1QXf7kcD8][Evergreen notes | Executable strategy for writing]] :productivity:
