:PROPERTIES:
:ID:       a3aa643f-aac1-4078-b874-a68099d172e0
:END:
#+title: Rover

* Landing a Rover
Landing on Mars is challenging because there's is too much
atmosphere to be ignored, but too little to cushion the landing.
Hence, all Mars rovers will have a three phrases: Entry, Descent and
Landing (abbrieviated EDL). cite:lakdawalla18_curios

* TODO Read cite:systemsengineering_6575245

* How the Curiosity Rover worked

- Lots of redundancy. A-side and B-side electronics.
- The battery was a [[https://en.wikipedia.org/wiki/Multi-mission_radioisotope_thermoelectric_generator][MMRTG battery]]. Curiosity used plutonium-238 as the
  nuclear fuel, and an array of thermocouples reliably converted the
  released heat into electricity with no moving parts.

Things to account for:

- Operating temperatures of each component. Scientists maintained a
  heating table, and also had schedules to ensure that the various
  parts were heated to operating temperature before functioning.
- Have a system collecting heat output from energy


bibliography:biblio.bib

