:PROPERTIES:
:ID:       8bc3bc49-5567-4694-8508-ff35d70db72a
:END:
#+title: Singapore Dollar Nominal Effective Exchange Rate
#+roam_alias: S$NEER

* Definition
S$NEER is the exchange rate between the Singdollar and a basket of currencies of
the country's major trading partners.

* Why manage S$NEER?

The Singapore economy is small and open, where gross export and import of goods
are more than 300% of GDP. Almost 40 cents of every dollar spent domestically go
into imports. This means exchange rate has a much higher influence on inflation
and price stability.

* What is done with S$NEER?

The Singdollar is allowed to appreciate and depreciate against this basket of
currencies, which it does not disclose, within a band. If the threshold is
crossed, the MAS will intervene.

* How is the S$NEER adjusted?

1. In 2008, the MAS flattened the slope of the S$NEER to prevent appreciation of the Singdollar
2. In 2009, they economic recession resulted in a sharp fall of inflation, and
   the band was moved downwards
3. In Apr 2010, the band was shifted to a positive slope, and upwards, following
   the recovery of the Singapore economy
