:PROPERTIES:
:ID:       05e349f3-34e8-4438-8a30-5e7d7dd8835a
:END:
#+title: Statistical Methods for Finance

- tags :: [[id:51187adb-36a9-448e-bee4-ed0975a46e0e][Finance]]

* Returns

Net Returns:

\begin{equation}
R_t = \frac{P_t}{P_{t-1}} - 1 = \frac{P_t - P_{t-1}}{P_{t-1}}
\end{equation}

$R_t \ge -1$: a 100% loss occurs if the asset becomes totally
worthless.


Gross Returns:

\begin{equation}
  \frac{P_t}{P_{t-1}} = 1 + R_t
\end{equation}

The gross return over the most recent $k$ periods is:

\begin{equation}
  1 + R_t(k) = \frac{P_t}{P_{t-k}} = (1 + R_t)\dots (1 + R_{t-k+1})
\end{equation}

Log Returns:

\begin{equation}
  r_t = \log (1 + R_t) = \log \frac{P_t}{P_{t-1}} = p_t - p_{t-1}
\end{equation}

\begin{equation}
r_t(k) = r_t + r_{t-1} + \dots + r_{t-k+1}
\end{equation}

log returns are similar for daily returns, less similar for yearly
returns, and  not necessarily similar for multi-year returns.

** Random Walk Model

In the random walk model, single-period log returns are assumed to be
independent:

\begin{align} \label{eq:rw}
  1 + R_t(k) &= (1 + R_t)\dots(1 + R_{t-k+1}) \\
             &= \textrm{exp}(r_t) \dots \textrm{exp}(r_{t-k+1}) \\
             &= \textrm{exp}(r_t + \dots + r_{t-k+1})
\end{align}

It is also sometimes assumed that log returns are $N(\mu,\sigma^2)$
for some constant mean and variance. Then $k$ period log returns are
$N(k\mu, k\sigma^2)$.

** Geometric Random Walks

From eqref:eq:rw, we have that

\begin{equation}
  \frac{P_t}{P_{t-k}} = 1 + R_t(k) = \textrm{exp}(r_t + \dots + r_{t-k+1})
\end{equation}

A process whose logarithm is a random walk is called a geometric
random walk. If $r_1$, $r_2$, $\dots$ are i.i.d $N(\mu, \sigma^2)$,
then $P_t$ is lognormal for all $t$ and the process is a lognormal
geometric random walk. $\mu$ is called the log-mean, and $\sigma^2$
the log-standard deviation of thet lognormal distribution of
$exp(r_t)$.

** Validity of the Random Walk Model

In the lognormal geometric random walk model we assume that:

1. log returns are normally distributed
2. log returns are mutually independent


