#+SETUPFILE: ./hugo_setup.org
#+TITLE: General Talks

* Renn Vara - The Reality of Startup Life
Date: <2018-09-24 Mon>

Questions:
1. Why did you join a startup?
  - impact

Master the ability to communicate ideas, influence, and make things
happen. This is important because there isn't a luxury of time.

Activity: Tell a story: here's what I'm most challenged by in this
culture. The other person, ask how and what questions.

Next, the other person says "If I understand you correctly, (repeat
whatever was said). End with a question."

We don't have time to be misunderstood in a startup. The advantage of
a startup is speed. Value speed.

Inside a startup, seeking understanding is crucial. We spend too much
time, judging, making mistakes.

Make a commitment to seeking understanding as the number 1 priority:
active listening.

Activity: Ask if you can offer your point of view. 

Feedback is important. Active listening is important.

 Accountability is important. Do what you say you're going to do. 3
words women want to hear from men: I got this (not I love you).
