:PROPERTIES:
:ID:       8caa7d17-dfc0-4535-9016-8bd52892ff58
:END:
#+hugo_slug: the_intelligent_investor
#+title: The Intelligent Investor

- author :: [[id:f87d978f-2ecf-44ef-acee-92a07ec8720f][Benjamin Graham]]
- tags :: [[id:51187adb-36a9-448e-bee4-ed0975a46e0e][Finance]]
* Book Notes
:PROPERTIES:
:NOTER_DOCUMENT: /home/jethro/Dropbox/Calibre/Benjamin Graham, Jason Zweig/The Intelligent Investor (222)/The Intelligent Investor - Benjamin Graham, Jason Zweig.pdf
:NOTER_PAGE: 126
:END:

** Being an intelligent investor is about developing emotional discipline
:PROPERTIES:
:NOTER_PAGE: 29
:END:

An intelligent investor refuses to stoop to the market's level of irrationality.
They minimize the odds of irreversible gains, and maximize the odds of achieving
sustainable gains.

** Investor vs Speculator
:PROPERTIES:
:NOTER_PAGE: (50 . 0.3885102239532619)
:END:

The investor must recognize the existence of a /speculative factor/ in their common-stock holdings, and keep this components within minor limits.

The defensive investor must confine himself to the shares of important companies with a long record of profitable operations and in strong financial condition.

1. Always thoroughly analyse a company, and the soundness of the underlying businesses, before buying its stock.
2. Deliberate protect yourself against serious losses
3. aspire to "adequate", not extraordinary performance

** The stock market is riskier when prices are higher
:PROPERTIES:
:NOTER_PAGE: (96 . 0.46056475170399225)
:END:

** Stock market performance factors
:PROPERTIES:
:NOTER_PAGE: (100 . 0.1733203505355404)
:END:

The performance of a stock market is dependent on 3 factors:

1. Real growth (rise of company's earnings and dividends)
2. Inflationary growth (rise of prices throughout the economy)
3. Speculative growth (increase or decrease in the investing public's appetite for stocks)

** Combating Inflation

Mild inflation allows companies to pass the increased costs of their own raw
materials on to customers, but high inflation wreaks havoc-forcing customers to
slash their purchases, depressing activity throughout the economy.

To guard against inflation, a common advice is to buy stocks, but in truth
stocks failed to keep up with inflation about one-fifth of the time.

To combat inflation, additionally look into [[id:ea338d3f-f51e-49f4-b962-203996d96a25][REITs]], and government bonds.
