#+setupfile:./hugo_setup.org
#+hugo_slug: now
#+title: What I'm Doing Now

This is a regularly updated log of what I'm currently looking into.

- Looking into the deep ends of [[file:lit/robot_grasping.org][Robot Grasping]] and [[file:lit/bin_picking.org][Bin Picking]]. My task is
  pretty specific and simple for now, but I'm still getting used to ROS, and
  trying to setup a simple controller for the robot.
- Keeping tabs on [[file:lit/event_based_vision.org][Event-based Vision]] and other things to do with neuromorphic
  hardware. I think there is a strong future in event-based sensing with
  low-power robotics, and also with tasks that require high temporal resolution
  such as slippage detection.
- Working on [[https://www.orgroam.com/][Org-roam]], as usual. Developmental progress on it has sort of
  stalled. Now that I'm getting back into research, the flaws and things I want
  are starting to show, and I want to sit on my workflow a bit more before
  upgrading Org-roam to fit it better.
- Pruning this digital garden. There are a lot of unnecessary notes. It always
  feels wasteful to delete notes, but I think it will eventually be for the
  best.
