:PROPERTIES:
:ID:       96b9e89f-f1e9-4f1e-ba0c-4697c3f2fb12
:END:
#+title: Wisdom

* [[https://www.youtube.com/watch?v=3qHkcs3kG44][Joe Rogan Experience #1309 - Naval Ravikant]]

1. The greatest artists are able to start over. If you're not doing
   that, you're just getting older. When it's a dead-end, it's the
   right thing to do, even when you feel like you're almost there.
2. We tend to define people by narrow identities, even though people
   are broader than that.
3. Books read is a vanity metric. Read whatever satisfies your general
   curiousity, and for understanding. Look for ideas, things you don't
   understand, and research it.
4. We're always signalling, looking at what other people see of us,
   rather than looking at what we are. Social media is making
   celebrities of all of us, and celebrities are the among the most
   miserable people in the world.
5. Social contracts are powerful. When you tell people what you're
   going to do, you're generally serious about it.
6. The retirement that people want is not being old and sitting in a
   nursing home.  Retirement is when you stop sacrificing today for
   something imaginary tomorrow.
7. When you're unhappy, look at the underlying desire that in
   unfulfilled. It's okay to have desires, but not too many. Pick the
   one overwhelming desire.
8. To achieve peak performance, you must need to learn to optimize
   both the body and the mind. Keeping calm involves letting go of
   desires.
9. Intellectual athletes need to work and rest. Cranking out work
   everyday is not for humans, it's for machines.
10. You're not going to get rich renting out your time. You need to
    own a piece of business to gain your financial freedom.
11. In the hunter-gatherer age, we worked for ourselves. The
    industrial age created a model of thousands of people working on
    one thing. If somebody can tell you when you have to go to work,
    what you have to wear, you're not truly free.
12. [[https://www.investopedia.com/terms/c/coase-theorem.asp][Coase Theorem]] (??)
* [[https://twitter.com/sama/status/1214274038933020672?s=20]["How To Be Successful (At Your Career, Twitter Edition)"]]
