#+SETUPFILE:./hugo_setup.org
#+TITLE: Writing Papers

The following content is summarized from "How To Write a Technical
Paper" cite:Whiteside2017HowTW.

* Abstract
The abstract is what the reader reads to determine if the paper is
worthy of merit for further study. It should contain:

1. Brief introduction describing the discipline
2. A concise statement of the problem
3. A brief explanation of the solution and its key ideas
4. A brief description of the results obtained and their impacts

* Introduction
Gives background on and motivation for research, establishing its
importance. Consider technological trends, recent promising
developments. 

The summary should include a problem description, which is more
detailed than the abstract. Close with a description of the paper
outline, what sections it contains and what the reader will find in each.

* Related Work
- Shows what has happened in the field
- Provides a critique of the approaches in the literature

* System Model
Describes all hypotheses and assumptions of the environment on which
the problem will be stated. Realize both explicit and implicit
assumptions.

* Problem Statement
State the problem clearly, being as exact as possible.

* Solution
First, provide an overview of the solution. Give rationale, explain
concepts and mechanisms. Next, provide a detailed description of the
solution and its functionality. Figures are often helpful.

* Analysis
Perform qualitative and quantitative analysis on the solution. This
includes proof of correctness, and performance analysis.

* Simulation and Experimentation
Establish that the experimental setup is statistically stable. Explain
each experiment and caption each figure appropriately.

* Conclusion
The conclusion sections elaborates on the impacts of using your
approach. It also states limitations or disadvantages of your
solution, and enables you to provide directions for future research in
the field.


bibliography:./biblio/writing.bib
