:PROPERTIES:
:ID:       a4388398-3a2a-4686-ae7a-b1ae5030ba94
:END:
#+roam_key: http://www.cs.virginia.edu/~robins/YouAndYourResearch.html
#+hugo_slug: you_and_your_research
#+title: You and Your Research - Richard Hamming

- source :: http://www.cs.virginia.edu/~robins/YouAndYourResearch.html
- author :: [[id:b3b67b6b-d063-46e5-85b4-a06ee5e65404][Richard Hamming]]
- tags :: [[id:63384aa8-5da8-41c5-96aa-17f7925c274f][Research]]

#+begin_quote
Our society frowns on people who set out to do really good work.
You're not supposed to; luck is supposed to descend on you and you do
great things by chance. -- Richard Hamming
#+end_quote

#+begin_quote
Luck favours the prepared mind -- Pasteur
#+end_quote

One of the characteristics of successful scientists is having courage. They will go forward under incredible circumstances, they think and continue to think.

Many mathematicians, theoretical physicists and astrophysicists do their best work when they are young. *When you are famous, it is hard to work on small problems.* Great scientists often make this error.
After information theory, what could Shannon possibly do for an encore?

*It is not sufficient to do a good job, you have to sell it.* You have to learn to write clearly and well so people will read it, you must learn to give reasonably formal talks, and you also must learn to give informal talks.

The people who do great work with less ability but who are committed to it, get more done than those who have great skill and dabble in it. 

Good scientists will fight the system rather than learn to work with the systm and take advantage of all the system has to offer. Good scientists are also optimistic, on the lookout for the positive things, instead of the negative.

In conclusion:

#+begin_quote
I claim that some of the reasons why so many people who have greatness within their grasp don't succeed are: they don't work on important problems, they don't become emotionally involved, they don't try and change what is difficult to some other situation which is easily done but is still important, and they keep giving themselves alibis why they don't. -- Richard Hamming
#+end_quote
