:PROPERTIES:
:ID:       c03178ca-c893-4c48-9bd7-3b4f928ca45c
:END:
#+title: zhu_ev-flownet_2018: EV-FlowNet: self-supervised optical flow estimation for event-based cameras
#+roam_key: cite:zhu_ev-flownet_2018

* EV-FlowNet: self-supervised optical flow estimation for event-based cameras
  :PROPERTIES:
  :Custom_ID: zhu_ev-flownet_2018
  :URL: http://arxiv.org/abs/1802.06898
  :AUTHOR: Zhu, A. Z., Yuan, L., Chaney, K., & Daniilidis, K.
  :NOTER_DOCUMENT: /home/jethro/Zotero/storage/X9P55F47/Zhu et al. - 2018 - EV-FlowNet Self-Supervised Optical Flow Estimatio.pdf
  :NOTER_PAGE: 4
  :END:
** Event data is well-suited for Optical Flow Estimation
:PROPERTIES:
:NOTER_PAGE: (1 . 0.6910112359550562)
:END:

By directly measuring the precise time at which the pixel changes, the event stream encodes fine-grained motion information. For example, optical flow can be estimated from a local window around each event in a linear fashion.
** Key Ideas
:PROPERTIES:
:NOTER_PAGE: (1 . 0.7397003745318352)
:END:

The authors propose a novel representation of event data, as an image with
channels representing the number of events, and the latest timestamp at each
polarity at each pixel. This preserves spatial relationships between events,
while maintaining the most recent temporal information at each pixel, and
providing a fixed number of channels for any event stream.

They also introduced a [[id:eecde484-c101-40f6-a099-9cf4a95b832a][Self-supervised Learning]] method, using a photometric loss
as a supervisory signal, without supervision from ground-truth flow.

** Event Representation
:PROPERTIES:
:NOTER_PAGE: (3 . 0.6347517730496455)
:END:

The event stream is represented as a 4 channel image:

1. Number of positive polarity events
2. Number of negative polarity events
3. Timestamp of most recent positive event
4. Timestamp of most negative event

This is similar to "Event-based Time Surfaces" cite:lagorce_hots_2017 and "Timestamp Images" cite:park_performance_2016

bibliography:biblio.bib
